// SPEC LINK: docs/specs/01-pipeline/47_pipeline_script_protocol.md §5 (AI-operator docs infrastructure)
//
// Drift guard (WF2 P10-3): docs/reference/data-lineage-map.md is GENERATED by
// scripts/generate-lineage-docs.mjs from the committed snapshot
// scripts/seeds/lineage-meta-snapshot.json (itself refreshed from
// pipeline_runs.records_meta.pipeline_meta via `--refresh`). Rendering is
// DB-free so this test is deterministic: it regenerates the doc from the
// committed snapshot and fails if the committed doc has drifted.
import { describe, it, expect } from 'vitest';
import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const REPO_ROOT = path.resolve(__dirname, '../../');
const GENERATOR = path.join(REPO_ROOT, 'scripts', 'generate-lineage-docs.mjs');
const SNAPSHOT = path.join(REPO_ROOT, 'scripts', 'seeds', 'lineage-meta-snapshot.json');
const DOC = path.join(REPO_ROOT, 'docs', 'reference', 'data-lineage-map.md');

describe('data-lineage map — drift guard (P10-3)', () => {
  it('generator, snapshot, and committed doc exist', () => {
    expect(fs.existsSync(GENERATOR)).toBe(true);
    expect(fs.existsSync(SNAPSHOT)).toBe(true);
    expect(fs.existsSync(DOC)).toBe(true);
  });

  it('committed doc matches a fresh render from the committed snapshot', () => {
    let failed = false;
    let output = '';
    try {
      output = execFileSync('node', [GENERATOR, '--check'], { cwd: REPO_ROOT, encoding: 'utf-8' });
    } catch (err) {
      failed = true;
      output = ((err as { stdout?: string }).stdout ?? '') + ((err as { stderr?: string }).stderr ?? '');
    }
    expect(
      failed,
      `data-lineage-map.md is STALE — run \`npm run lineage-docs\` (or --refresh). Output:\n${output}`,
    ).toBe(false);
  });
});
