/**
 * SPEC LINK: docs/specs/01-pipeline/61_source_heritage_properties.md (§8c, §9, §12)
 * Source-structure (infra) locks for the converted load_heritage step + its wiring —
 * pins the Spec 61 §8c decisions (DEC-A/C/D/I/K/M) against silent regressions.
 *
 * RE-POINTED at batch-2 row 3.4 ② (2026-09-30): the 808-line loader is now the frozen
 * shell scripts/load-heritage.js + scripts/load-heritage.descriptor.json (declared data)
 * + scripts/lib/compute/load-heritage.js (domain logic). Each lock below asserts the SAME
 * fact against its new home; none is dropped.
 */
import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';

const root = join(__dirname, '..', '..');
const read = (...p: string[]) => readFileSync(join(root, ...p), 'utf8');
// eslint-disable-next-line @typescript-eslint/no-require-imports
const descriptor = require('../../scripts/load-heritage.descriptor.json');
const shell = () => read('scripts', 'load-heritage.js');
const computeSrc = () => read('scripts', 'lib', 'compute', 'load-heritage.js');
const checkIds = (): string[] => descriptor.checks.map((c: { id: string }) => c.id);

describe('load_heritage — advisory lock + slug + version (DEC-A/C/D)', () => {
  it('lock 61 (spec-number convention, NOT spec L4=62): shell constant + descriptor identity agree', () => {
    expect(shell()).toMatch(/ADVISORY_LOCK_ID\s*=\s*61\b/);
    expect(shell()).not.toMatch(/ADVISORY_LOCK_ID\s*=\s*62\b/);
    expect(descriptor.identity.lock).toBe(61);
  });
  it('slug is load_heritage; the sources chain ledger name is sources:load_heritage (DEC-C, pre-empts #409)', () => {
    expect(descriptor.identity.name).toBe('load_heritage');
    expect(Object.keys(descriptor.execution.invocation)).toEqual(['sources']);
    expect(descriptor.identity.name).not.toBe('source-heritage');
  });
  it('spec_version 1.1 (consumer §8d L23 pins on it; NOT the §3.1 stale 1.0)', () => {
    expect(descriptor.identity.spec_version).toBe('1.1');
    expect(descriptor.emits[0].skeleton.spec_version).toBe('1.1');
  });
  // MQ-B4 (a), registry-truth fold 19 (operator 2026-10-04): the phase is the 1-based position in
  // manifest chains.sources (generated by scripts/generate-sharing-phase.js), no longer the lock
  // number 61 — the expectation is derived here, never hand-typed.
  it('audit_table phase = the 1-based manifest position in chains.sources (derived, MQ-B4 (a))', () => {
    const manifest = JSON.parse(read('scripts', 'manifest.json')) as { chains: Record<string, string[]> };
    const pos = (manifest.chains.sources ?? []).indexOf('load_heritage') + 1;
    expect(pos, 'load_heritage is not in manifest chains.sources').toBeGreaterThan(0);
    expect(descriptor.sharing.varies_by_chain.phase).toEqual({ sources: pos });
  });
});

describe('load_heritage — frozen records_meta + counters (DEC-D)', () => {
  const reg = descriptor.emits[0].skeleton.heritage_register;
  const hcd = descriptor.emits[0].skeleton.heritage_districts;
  it('uses features_* counter names (H-v1.1.3), never polygons_*', () => {
    for (const sub of [reg, hcd]) {
      expect(Object.keys(sub)).toEqual(expect.arrayContaining(['features_inserted', 'features_updated', 'features_deleted']));
    }
    expect(JSON.stringify(descriptor.emits)).not.toMatch(/polygons_(inserted|updated|deleted)/);
    expect(computeSrc()).not.toMatch(/polygons_(inserted|updated|deleted)/);
  });
  it('records_total/new/updated are the combined feature / inserted / updated counts', () => {
    expect(descriptor.counters.records_total.source).toBe(
      'records_meta.heritage_load.heritage_register.feature_count + records_meta.heritage_load.heritage_districts.feature_count',
    );
    expect(descriptor.counters.records_new.source).toBe('written.inserted');
    expect(descriptor.counters.records_updated.source).toBe('written.updated');
  });
  it('heritage_load has per-dataset sub-blocks with the §9 frozen field names (the specSub rename)', () => {
    expect(Object.keys(reg)).toEqual(expect.arrayContaining(['filtered_out_listed', 'unknown_status_count']));
    expect(Object.keys(hcd)).toEqual(expect.arrayContaining(['filtered_out_appeal_study', 'unknown_hcd_type_count']));
    expect(descriptor.inputs.reads.externals.map((e: { id: string }) => e.id)).toEqual(['heritage_register', 'heritage_districts']);
  });
});

describe('load_heritage — audit rows (DEC-I: load-side only; unknown_* WARN)', () => {
  const byId = (id: string) => descriptor.checks.find((c: { id: string }) => c.id === id);
  it('declares the named LOAD-side rows', () => {
    for (const m of [
      'heritage_register_feature_count', 'heritage_districts_feature_count', 'heritage_filtered_listed_pct',
      'heritage_geometry_skipped_pct', 'heritage_count_drift_pct', 'heritage_mass_delete_pct',
      'heritage_geometry_update_pct', 'heritage_dataset_age_years',
    ]) {
      expect(checkIds()).toContain(m);
    }
  });
  it('does NOT declare the enrich-side rows (heritage_points_no_parcel_match / permit_type_heritage_disagreement)', () => {
    expect(checkIds()).not.toContain('heritage_points_no_parcel_match');
    expect(checkIds()).not.toContain('permit_type_heritage_disagreement');
  });
  it('unknown_status_count + unknown_hcd_type_count are WARN rows (reach the cascade)', () => {
    expect(byId('heritage_unknown_status_count').severity).toBe('WARN');
    expect(byId('heritage_unknown_hcd_type_count').severity).toBe('WARN');
  });
  it('heritage_address_coerced_empty_count is a WARN row (DEC-M)', () => {
    expect(byId('heritage_address_coerced_empty_count').severity).toBe('WARN');
  });
  it('duplicate-source-id WARN rows per dataset (review fold)', () => {
    expect(byId('heritage_register_duplicate_source_id_count').severity).toBe('WARN');
    expect(byId('heritage_districts_duplicate_source_id_count').severity).toBe('WARN');
  });
  it('L14 first-run zero-feature guard is a pre_write FAIL (review fold)', () => {
    expect(byId('heritage_zero_features_first_run')).toMatchObject({ severity: 'FAIL', when: 'pre_write' });
  });
  it('a skip re-pins spec_version after the prior spread (DEC-K / load-ravines BUG-2)', () => {
    expect(computeSrc()).toMatch(/\.\.\.\(lane\.prior \|\| \{\}\), spec_version: SPEC_VERSION/);
  });
  it('count-drift + mass-delete FAIL is threshold-derived (config-bound; the override never suppresses)', () => {
    expect(byId('heritage_count_drift_pct')).toMatchObject({ severity: 'FAIL', limit_from_config: 'load_heritage_count_drift_fail_pct' });
    expect(byId('heritage_mass_delete_pct')).toMatchObject({ severity: 'FAIL', limit_from_config: 'load_heritage_mass_delete_fail_pct' });
  });
});

describe('load_heritage — geometry + null-safety (DEC-E/M)', () => {
  const write = (t: string) => descriptor.outputs.writes.find((w: { table: string }) => w.table === t);
  it('validation is the library point / polygon arms (not geometry-validator.js)', () => {
    expect(write('heritage_properties').geometry_kind).toBe('point');
    expect(write('heritage_districts').geometry_kind).toBe('polygon');
    expect(computeSrc()).not.toMatch(/require\([^)]*geometry-validator/);
    expect(shell()).not.toMatch(/require\([^)]*geometry-validator/);
  });
  it('both datasets are CKAN externals (the emitMeta CKAN external, now declared data)', () => {
    for (const e of descriptor.inputs.reads.externals) {
      expect(e.url).toMatch(/^https:\/\/ckan0\.cf\.opendata\.inter\.prod-toronto\.ca\//);
    }
    // execution.network.egress deleted in the Phase 3 RE-FREEZE (#47, zero runtime readers)
  });
  it('the compute reaches no network (fetch is the library acquisition seam)', () => {
    expect(computeSrc()).not.toMatch(/\bfetch\(/);
    expect(computeSrc()).not.toMatch(/require\(['"]node-fetch['"]\)/);
  });
  it('#426: register source_id keyed on Folder_Row, NOT the dropped OBJECTID', () => {
    expect(descriptor.inputs.reads.externals[0].key_property).toBe('Folder_Row');
    expect(descriptor.inputs.reads.externals[0].key_property).not.toBe('OBJECTID');
  });
});

describe('migration 170 + manifest wiring', () => {
  it('migration 170 creates both tables, the function + extension; bylaw_no/designated_date nullable', () => {
    const mig = read('migrations', '170_create_heritage_tables.sql');
    expect(mig).toMatch(/CREATE EXTENSION IF NOT EXISTS fuzzystrmatch/);
    expect(mig).toMatch(/CREATE OR REPLACE FUNCTION normalize_address/);
    expect(mig).toMatch(/CREATE TABLE IF NOT EXISTS heritage_properties/);
    expect(mig).toMatch(/CREATE TABLE IF NOT EXISTS heritage_districts/);
    // designated_date on heritage_districts is NULLABLE (no NOT NULL) — sentinel maps to NULL
    expect(mig).not.toMatch(/designated_date\s+DATE NOT NULL/);
    // DOWN never drops the shared extension
    expect(mig).not.toMatch(/DROP EXTENSION/);
  });
  it('manifest registers load_heritage in the sources chain after load_ravines', () => {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const manifest = require('../../scripts/manifest.json');
    expect(manifest.scripts.load_heritage.file).toBe('scripts/load-heritage.js');
    const sources = manifest.chains.sources;
    expect(sources).toContain('load_heritage');
    expect(sources.indexOf('load_heritage')).toBe(sources.indexOf('load_ravines') + 1);
  });
});
