// SPEC LINK: docs/specs/02-web-admin/86_control_panel.md §5 Phase 3
// SPEC LINK: docs/specs/01-pipeline/124_step_standard_policy.md (Rule 3, "the admin intersection")
//
// Drift guard (WF2 "Admin Tunable Coverage" commit 3): GlobalConfigCard's
// GROUPS is now derived from
// src/features/admin-controls/generated/logic-variable-groups.json, itself
// generated by scripts/generate-logic-variable-groups.mjs from the seed's
// declared `admin.group` field. A generated artifact that can silently rot
// (seed edited, generator not re-run) is exactly the failure mode this
// mechanism exists to prevent — this test regenerates to a buffer (--check
// mode, no write) and fails if the committed JSON is stale.
import { describe, it, expect } from 'vitest';
import { execFileSync, spawnSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const REPO_ROOT = path.resolve(__dirname, '../../');
const GENERATOR = path.join(REPO_ROOT, 'scripts', 'generate-logic-variable-groups.mjs');
const GENERATED_JSON = path.join(
  REPO_ROOT,
  'src',
  'features',
  'admin-controls',
  'generated',
  'logic-variable-groups.json',
);

describe('logic-variable-groups — drift guard (WF2 admin tunable coverage, commit 3)', () => {
  it('generator and committed JSON exist', () => {
    expect(fs.existsSync(GENERATOR)).toBe(true);
    expect(fs.existsSync(GENERATED_JSON)).toBe(true);
  });

  it('committed JSON is up to date (regenerate → identical)', () => {
    // --check exits non-zero if the committed JSON differs from a fresh render
    // OR if the GROUP_ORDER/seed cross-validation throws (a seed key declares
    // a group it isn't pinned under, or vice versa).
    let failed = false;
    let output = '';
    try {
      output = execFileSync('node', [GENERATOR, '--check'], {
        cwd: REPO_ROOT,
        encoding: 'utf-8',
      });
    } catch (err) {
      failed = true;
      output = (err as { stdout?: string; stderr?: string }).stdout ?? '';
      output += (err as { stderr?: string }).stderr ?? '';
      output += String((err as { message?: string }).message ?? '');
    }
    expect(
      failed,
      `logic-variable-groups.json is STALE (or the seed/GROUP_ORDER cross-check failed) — run \`npm run logic-var-groups\`. Generator output:\n${output}`,
    ).toBe(false);
  });

  it('RED — a stale/tampered JSON fires --check exit 1 (real CLI, not just the exported function)', () => {
    // BUILDO_LOGIC_VAR_GROUPS_PATH points the generator at a throwaway temp
    // file instead of the real committed artifact — mirrors
    // BUILDO_CHURN_TABLE_PATH's use in the PH-2 churn-complexity RED fixture
    // (step-conformance.infra.test.ts) — never mutates the real committed JSON.
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'logic-var-groups-fixture-'));
    const badPath = path.join(dir, 'stale-logic-variable-groups.json');
    fs.writeFileSync(badPath, '[]\n');
    const run = spawnSync('node', [GENERATOR, '--check'], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
      timeout: 60_000,
      env: { ...process.env, BUILDO_LOGIC_VAR_GROUPS_PATH: path.relative(REPO_ROOT, badPath) },
    });
    expect(run.status, `the checker did not fire on a stale fixture; stdout=${run.stdout} stderr=${run.stderr}`).toBe(1);
    expect(run.stderr + run.stdout).toContain('STALE');
  });
});
