// SPEC LINK: docs/specs/01-pipeline/47_pipeline_script_protocol.md §5 (AI-operator docs infrastructure)
//
// Drift guard (WF2 P10-1): docs/reference/logic-variables-registry.md is
// GENERATED by scripts/generate-logic-vars-docs.mjs from the seed JSON +
// migration-only vars + per-script LOGIC_VARS_SCHEMA unions. A generated doc
// that can silently rot is exactly the failure mode this WF spent P1-P6.7
// fixing in the specs. This test regenerates to a buffer (--check mode, no
// write) and fails if the committed doc is stale — generated means gated.
import { describe, it, expect } from 'vitest';
import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

const REPO_ROOT = path.resolve(__dirname, '../../');
const GENERATOR = path.join(REPO_ROOT, 'scripts', 'generate-logic-vars-docs.mjs');
const DOC = path.join(REPO_ROOT, 'docs', 'reference', 'logic-variables-registry.md');

describe('logic-variables registry — drift guard (P10-1)', () => {
  it('generator and committed doc exist', () => {
    expect(fs.existsSync(GENERATOR)).toBe(true);
    expect(fs.existsSync(DOC)).toBe(true);
  });

  it('committed doc is up to date (regenerate → identical)', () => {
    // --check exits non-zero if the committed doc differs from a fresh render.
    let failed = false;
    let output = '';
    try {
      output = execFileSync('node', [GENERATOR, '--check'], {
        cwd: REPO_ROOT,
        encoding: 'utf-8',
      });
    } catch (err) {
      failed = true;
      output = (err as { stdout?: string; stderr?: string }).stdout ?? '';
      output += (err as { stderr?: string }).stderr ?? '';
    }
    expect(
      failed,
      `logic-variables-registry.md is STALE — run \`npm run logic-vars-docs\`. Generator output:\n${output}`,
    ).toBe(false);
  });
});
