// SPEC LINK: docs/specs/02-web-admin/86_control_panel.md §5 Phase 3
// SPEC LINK: docs/specs/01-pipeline/124_step_standard_policy.md (Rule 3, "the admin intersection")
//
// Drift guard (WF2 "Admin Tunable Coverage" commit 3): GlobalConfigCard's
// GROUPS is now derived from
// src/features/admin-controls/generated/logic-variable-groups.json, itself
// generated by scripts/generate-logic-variable-groups.mjs from the seed's
// declared `admin.group` field. A generated artifact that can silently rot
// (seed edited, generator not re-run) is exactly the failure mode this
// mechanism exists to prevent — this test regenerates to a buffer (--check
// mode, no write) and fails if the committed JSON is stale.
import { describe, it, expect } from 'vitest';
import { execFileSync, spawnSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const REPO_ROOT = path.resolve(__dirname, '../../');
const GENERATOR = path.join(REPO_ROOT, 'scripts', 'generate-logic-variable-groups.mjs');
const GENERATED_JSON = path.join(
  REPO_ROOT,
  'src',
  'features',
  'admin-controls',
  'generated',
  'logic-variable-groups.json',
);

describe('logic-variable-groups — drift guard (WF2 admin tunable coverage, commit 3)', () => {
  it('generator and committed JSON exist', () => {
    expect(fs.existsSync(GENERATOR)).toBe(true);
    expect(fs.existsSync(GENERATED_JSON)).toBe(true);
  });

  it('committed JSON is up to date (regenerate → identical)', () => {
    // --check exits non-zero if the committed JSON differs from a fresh render
    // OR if the GROUP_ORDER/seed cross-validation throws (a seed key declares
    // a group it isn't pinned under, or vice versa).
    let failed = false;
    let output = '';
    try {
      output = execFileSync('node', [GENERATOR, '--check'], {
        cwd: REPO_ROOT,
        encoding: 'utf-8',
      });
    } catch (err) {
      failed = true;
      output = (err as { stdout?: string; stderr?: string }).stdout ?? '';
      output += (err as { stderr?: string }).stderr ?? '';
      output += String((err as { message?: string }).message ?? '');
    }
    expect(
      failed,
      `logic-variable-groups.json is STALE (or the seed/GROUP_ORDER cross-check failed) — run \`npm run logic-var-groups\`. Generator output:\n${output}`,
    ).toBe(false);
  });

  it('RED — a stale/tampered JSON fires --check exit 1 (real CLI, not just the exported function)', () => {
    // BUILDO_LOGIC_VAR_GROUPS_PATH points the generator at a throwaway temp
    // file instead of the real committed artifact — mirrors
    // BUILDO_CHURN_TABLE_PATH's use in the PH-2 churn-complexity RED fixture
    // (step-conformance.infra.test.ts) — never mutates the real committed JSON.
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'logic-var-groups-fixture-'));
    const badPath = path.join(dir, 'stale-logic-variable-groups.json');
    fs.writeFileSync(badPath, '[]\n');
    const run = spawnSync('node', [GENERATOR, '--check'], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
      timeout: 60_000,
      env: { ...process.env, BUILDO_LOGIC_VAR_GROUPS_PATH: path.relative(REPO_ROOT, badPath) },
    });
    expect(run.status, `the checker did not fire on a stale fixture; stdout=${run.stdout} stderr=${run.stderr}`).toBe(1);
    expect(run.stderr + run.stdout).toContain('STALE');
  });

  // WF2 ADMIN-1 ratchet, batch 1 (§4.4/R-8 known-bad-fixture gap): the
  // KNOWN_GROUP_LABELS set in logic-var-admin-declarations.logic.test.ts is
  // DERIVED from the seed itself, so a seed-wide typo'd label is vacuously
  // green there. The real authority is THIS generator's GROUP_ORDER
  // cross-validation — a seed key declaring admin.group = X where X is not
  // pinned anywhere in GROUP_ORDER must THROW, never silently spawn a new
  // 1-key group. BUILDO_LOGIC_VARS_SEED_PATH points the generator at a
  // tampered temp copy of the real seed; the real committed seed is never
  // mutated.
  it('RED — a seed key naming a group absent from GROUP_ORDER throws (not silently accepted)', () => {
    const realSeed = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'scripts', 'seeds', 'logic_variables.json'), 'utf-8'));
    // A brand-new fake key, never a member of GROUP_ORDER by construction —
    // robust regardless of how much of the ADMIN-1 ratchet has landed (an
    // arbitrary REAL key might already be pinned somewhere and would instead
    // trip the FORWARD-direction mismatch check, a different, also-valid
    // throw, but not the REVERSE-direction one this fixture targets; and once
    // the ratchet reaches 0 there is no admin.hidden key left to reuse).
    const fakeKey = '___wf2_admin1_ratchet_fixture_key_never_in_seed___';
    expect(realSeed[fakeKey], 'fixture key collided with a real seed key — pick a different name').toBeUndefined();
    const tampered = { ...realSeed, [fakeKey]: { default: 1, type: 'number', description: 'fixture only', min: 0, max: 1, admin: { group: '___NOT_PINNED_IN_GROUP_ORDER___' } } };
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'logic-var-groups-seed-fixture-'));
    const badSeedPath = path.join(dir, 'tampered-logic_variables.json');
    fs.writeFileSync(badSeedPath, JSON.stringify(tampered, null, 2) + '\n');
    const run = spawnSync('node', [GENERATOR, '--check'], {
      cwd: REPO_ROOT,
      encoding: 'utf8',
      timeout: 60_000,
      env: {
        ...process.env,
        BUILDO_LOGIC_VARS_SEED_PATH: path.relative(REPO_ROOT, badSeedPath),
        BUILDO_LOGIC_VAR_GROUPS_PATH: path.relative(REPO_ROOT, path.join(dir, 'throwaway-output.json')),
      },
    });
    expect(run.status, `the generator did not throw on an unpinned group label; stdout=${run.stdout} stderr=${run.stderr}`).not.toBe(0);
    expect(run.stderr + run.stdout).toContain('is not pinned in GROUP_ORDER');
  });
});
