import { query } from '@/lib/db/client';
import type { CoaApplication } from '@/lib/coa/types';

// ---------------------------------------------------------------------------
// CoA application data-access layer
// ---------------------------------------------------------------------------

/**
 * Insert a new CoA application into the database.
 *
 * The `id` and timestamp fields (`first_seen_at`, `last_seen_at`) are
 * generated by the database and returned in the result.
 */
export async function insertCoaApplication(
  app: Omit<CoaApplication, 'id' | 'created_at'>
): Promise<CoaApplication> {
  const rows = await query<CoaApplication>(
    `INSERT INTO coa_applications (
      application_number, address, street_num, street_name, ward,
      status, decision, decision_date, hearing_date, description,
      applicant, linked_permit_num, linked_confidence,
      first_seen_at, last_seen_at
    ) VALUES (
      $1, $2, $3, $4, $5,
      $6, $7, $8, $9, $10,
      $11, $12, $13,
      NOW(), NOW()
    )
    RETURNING
      id,
      application_number  AS application_num,
      address,
      street_num,
      street_name,
      ward,
      status,
      decision,
      decision_date,
      hearing_date,
      description,
      applicant,
      linked_permit_num,
      NULL                AS linked_permit_revision,
      linked_confidence   AS link_confidence,
      first_seen_at       AS created_at`,
    [
      app.application_num,
      app.address,
      app.street_num,
      app.street_name,
      app.ward,
      app.status,
      app.decision,
      app.decision_date,
      app.hearing_date,
      app.description,
      app.applicant,
      app.linked_permit_num,
      app.link_confidence,
    ]
  );

  return rows[0];
}

/**
 * Retrieve all CoA applications linked to a given building permit.
 *
 * Because the `coa_applications` table stores only `linked_permit_num`
 * (no separate revision column), the `revision_num` parameter is accepted
 * for interface consistency but is not used in the query filter.
 */
export async function getCoaByPermit(
  permit_num: string,
  _revision_num: string
): Promise<CoaApplication[]> {
  return query<CoaApplication>(
    `SELECT
      id,
      application_number  AS application_num,
      address,
      street_num,
      street_name,
      ward,
      status,
      decision,
      decision_date,
      hearing_date,
      description,
      applicant,
      linked_permit_num,
      NULL                AS linked_permit_revision,
      linked_confidence   AS link_confidence,
      first_seen_at       AS created_at
    FROM coa_applications
    WHERE linked_permit_num = $1
    ORDER BY hearing_date DESC`,
    [permit_num]
  );
}

/**
 * Retrieve CoA applications that have not yet been linked to a permit.
 *
 * @param limit  Maximum number of rows to return (default 100).
 */
export async function getUnlinkedApplications(
  limit: number = 100
): Promise<CoaApplication[]> {
  return query<CoaApplication>(
    `SELECT
      id,
      application_number  AS application_num,
      address,
      street_num,
      street_name,
      ward,
      status,
      decision,
      decision_date,
      hearing_date,
      description,
      applicant,
      linked_permit_num,
      NULL                AS linked_permit_revision,
      linked_confidence   AS link_confidence,
      first_seen_at       AS created_at
    FROM coa_applications
    WHERE linked_permit_num IS NULL
    ORDER BY first_seen_at ASC
    LIMIT $1`,
    [limit]
  );
}

/**
 * Link a CoA application to a building permit by updating its
 * `linked_permit_num` and `linked_confidence` columns.
 */
export async function updateCoaLink(
  coaId: number,
  permitNum: string,
  _revision: string,
  confidence: number
): Promise<void> {
  await query(
    `UPDATE coa_applications
     SET linked_permit_num = $1,
         linked_confidence = $2,
         last_seen_at      = NOW()
     WHERE id = $3`,
    [permitNum, confidence, coaId]
  );
}
