-- 129: Seed universal_stream_catalog from the locked v10 CSV (Spec 84 §2.5.h.2).
--
-- Split from migration 128 per Spec 42 §6.6.B seed migration contract — a
-- seed failure must NOT roll back the table create from 128. This
-- migration is re-runnable via ON CONFLICT (seq) DO NOTHING.
--
-- Source: docs/reports/spec_84_universal_stream_v10.csv (110 rows × 174
-- columns). Generated by _tmp_phase_b_seed_catalog.mjs, which preflights
-- the CSV (asserts 110 × 174) and maps empty cells to SQL NULL for
-- nullable columns (phase, bid_value, loop_marker, all 6 color/icon
-- columns, rows_count).
--
-- Regression-locks (Spec 84 §8.5 v10 BUG fixes embedded in the seed):
--   * seq 14 (Final & Binding): bid_value = 0.8 (v9 had 0 — contradiction fix)
--   * Block B9.C present (v9 had B9.A → B9.B → B9.D gap — labeling fix)
--   * seq 1-110 contiguous

-- ═══════════════════════════════════════════════════════════════════
-- UP
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO universal_stream_catalog (seq, source_row_num, lifecycle_group, group_label, lifecycle_block, block_label, lifecycle_stage, stage_label, source, status, phase, bid_value, loop_marker, group_color, group_icon, block_color, block_icon, stage_color, stage_icon, rows_count) VALUES
  (1, 70, 'C1', 'CoA Intake', 'B1.A', 'Applications', 'a', 'Received', 'coa.status', 'Application Received', 'P1', 0.9, '—', '#CFFAFE', '📨', '#CFFAFE', '📨', '#CFFAFE', '📨', 10),
  (2, 71, 'C1', 'CoA Intake', 'B1.A', 'Applications', 'b', 'Accepted', 'coa.status', 'Accepted', 'P1', 1, '—', '#CFFAFE', '📨', '#CFFAFE', '📨', '#CFFAFE', '📨', 279),
  (3, 72, 'C1', 'CoA Intake', 'B1.B', 'Hearing Prep', 'a', 'Notice Prep', 'coa.status', 'Prepare Notice', 'P2', 0.9, '—', '#CFFAFE', '📨', '#CFFAFE', '📨', '#CFFAFE', '📨', 54),
  (4, 73, 'C1', 'CoA Intake', 'B1.B', 'Hearing Prep', 'b', 'Notice Prepared', 'coa.status', 'Notice Prepared', 'P2', 0.9, '—', '#CFFAFE', '📨', '#CFFAFE', '📨', '#CFFAFE', '📨', 74),
  (5, 74, 'C1', 'CoA Intake', 'B1.B', 'Hearing Prep', 'c', 'Tentatively Scheduled', 'coa.status', 'Tentatively Scheduled', 'P2', 0.9, '—', '#CFFAFE', '📨', '#CFFAFE', '📨', '#CFFAFE', '📨', 118),
  (6, 75, 'C1', 'CoA Intake', 'B1.B', 'Hearing Prep', 'd', 'Hearing Scheduled', 'coa.status', 'Hearing Scheduled', 'P2', 0.9, '—', '#CFFAFE', '📨', '#CFFAFE', '📨', '#CFFAFE', '📨', 317),
  (7, 76, 'C1', 'CoA Intake', 'B1.B', 'Hearing Prep', 'e', 'Hearing Rescheduled', 'coa.status', 'Hearing Rescheduled', 'P2', 0.9, '↩ #75', '#CFFAFE', '📨', '#CFFAFE', '📨', '#CFFAFE', '📨', 1),
  (8, 77, 'C1', 'CoA Intake', 'B1.C', 'Hearing Pause', 'a', 'Postponed', 'coa.status', 'Postponed', 'P2', 0.7, '↩ #75', '#CFFAFE', '📨', '#CFFAFE', '📨', '#FEF9C3', '⏸️', 292),
  (9, 78, 'C1', 'CoA Intake', 'B1.C', 'Hearing Pause', 'b', 'Deferred', 'coa.status', 'Deferred', 'P2', 0.2, '↩ #75', '#CFFAFE', '📨', '#CFFAFE', '📨', '#FEF9C3', '⏸️', 270),
  (10, 79, 'C2', 'CoA Decision', 'B2.A', 'Consent', 'a', 'Conditional Consent', 'coa.status', 'Conditional Consent', 'P3', 0.8, '—', '#EDE9FE', '⚖️', '#EDE9FE', '⚖️', '#DCFCE7', '✅', 326),
  (11, 80, 'C2', 'CoA Decision', 'B2.B', 'Approved', 'a', 'Approved', 'coa.status', 'Approved', 'P3', 0.8, '—', '#EDE9FE', '⚖️', '#EDE9FE', '⚖️', '#DCFCE7', '✅', 246),
  (12, 81, 'C2', 'CoA Decision', 'B2.B', 'Approved', 'b', 'Approved + Conditions', 'coa.status', 'Approved with Conditions', 'P3', 0.8, '—', '#EDE9FE', '⚖️', '#EDE9FE', '⚖️', '#DCFCE7', '✅', 554),
  (13, 82, 'C2', 'CoA Decision', 'B2.C', 'Refused / Binding', 'a', 'Refused', 'coa.status', 'Refused', 'P19', 0, '—', '#EDE9FE', '⚖️', '#EDE9FE', '⚖️', '#FECACA', '❌', 59),
  (14, 83, 'C2', 'CoA Decision', 'B2.C', 'Refused / Binding', 'b', 'Final & Binding', 'coa.status', 'Final and Binding', 'P4', 0.8, '(terminal)', '#EDE9FE', '⚖️', '#EDE9FE', '⚖️', '#DCFCE7', '✅', 1),
  (15, 84, 'C3', 'CoA Post-Decision', 'B3.A', 'Appeal Window', 'a', 'Awaiting Expiry', 'coa.status', 'Await Expiry Date', 'P3', 0.8, '—', '#FEF9C3', '⏰', '#FEF9C3', '⏰', '#FEF9C3', '⏰', 24),
  (16, 85, 'C3', 'CoA Post-Decision', 'B3.B', 'Appeal Initiated', 'a', 'Appealed', 'coa.status', 'Appealed', 'P3', 0.2, '—', '#FEF9C3', '⏰', '#FEF9C3', '⏰', '#FEF9C3', '⏰', 1),
  (17, 86, 'C3', 'CoA Post-Decision', 'B3.C', 'Active Appeals', 'a', 'TLAB Appeal', 'coa.status', 'TLAB Appeal', 'P3', 0.1, '—', '#FEF9C3', '⏰', '#FEF9C3', '⏰', '#FEF9C3', '⏰', 347),
  (18, 87, 'C3', 'CoA Post-Decision', 'B3.C', 'Active Appeals', 'b', 'OMB Appeal', 'coa.status', 'OMB Appeal', 'P3', 0.05, '—', '#FEF9C3', '⏰', '#FEF9C3', '⏰', '#FEF9C3', '⏰', 218),
  (19, 88, 'C4', 'CoA Closure', 'B4.A', 'Terminal', 'a', 'Withdrawn', 'coa.status', 'Application Withdrawn', 'P19', 0, '(terminal)', '#E2E8F0', '🏁', '#E2E8F0', '🏁', '#FEE2E2', '🗑️', 904),
  (20, 89, 'C4', 'CoA Closure', 'B4.A', 'Terminal', 'b', 'Cancelled', 'coa.status', 'Cancelled', 'P19', 0, '(terminal)', '#E2E8F0', '🏁', '#E2E8F0', '🏁', '#FEE2E2', '🗑️', 1),
  (21, 90, 'C4', 'CoA Closure', 'B4.A', 'Terminal', 'c', 'Complete', 'coa.status', 'Complete', 'P20', 0.5, '(terminal)', '#E2E8F0', '🏁', '#E2E8F0', '🏁', '#E2E8F0', '🏁', 8),
  (22, 91, 'C4', 'CoA Closure', 'B4.A', 'Terminal', 'd', 'Closed', 'coa.status', 'Closed', 'P20', 0.5, '(terminal)', '#E2E8F0', '🏁', '#E2E8F0', '🏁', '#E2E8F0', '🏁', NULL),
  (23, 1, 'BP1', 'Permit Intake', 'B5.A', 'Initial Submission', 'a', 'Request Received', 'permits.status', 'Request Received', 'P3', 0.9, '—', '#DBEAFE', '📋', '#DBEAFE', '📋', '#DBEAFE', '📋', 1),
  (24, 2, 'BP1', 'Permit Intake', 'B5.A', 'Initial Submission', 'b', 'Application Received', 'permits.status', 'Application Received', 'P3', 0.9, '—', '#DBEAFE', '📋', '#DBEAFE', '📋', '#DBEAFE', '📋', 218),
  (25, 3, 'BP1', 'Permit Intake', 'B5.B', 'Submission Accepted', 'a', 'Application Acceptable', 'permits.status', 'Application Acceptable', 'P3', 1, '—', '#DBEAFE', '📋', '#DBEAFE', '📋', '#DBEAFE', '📋', 465),
  (26, 4, 'BP1', 'Permit Intake', 'B5.C', 'File Active', 'a', 'Open', 'permits.status', 'Open', 'P3', 0.9, '—', '#DBEAFE', '📋', '#DBEAFE', '📋', '#DBEAFE', '📋', 519),
  (27, 5, 'BP1', 'Permit Intake', 'B5.C', 'File Active', 'b', 'Active', 'permits.status', 'Active', 'P3', 0.9, '—', '#DBEAFE', '📋', '#DBEAFE', '📋', '#DBEAFE', '📋', 24),
  (28, 6, 'BP2', 'Plan Review', 'B6.A', 'Review Queued', 'a', 'Not Started', 'permits.status', 'Not Started', 'P7d', 0.9, '—', '#E0E7FF', '🔍', '#E0E7FF', '🔍', '#E5E7EB', '🐛', NULL),
  (29, 7, 'BP2', 'Plan Review', 'B6.A', 'Review Queued', 'b', 'Not Started - Express', 'permits.status', 'Not Started - Express', 'P7d', 0.9, '—', '#E0E7FF', '🔍', '#E0E7FF', '🔍', '#E5E7EB', '🐛', 92),
  (30, 8, 'BP2', 'Plan Review', 'B6.B', 'Review In Progress', 'a', 'Under Review', 'permits.status', 'Under Review', 'P4', 0.9, '—', '#E0E7FF', '🔍', '#E0E7FF', '🔍', '#E0E7FF', '🔍', NULL),
  (31, 9, 'BP2', 'Plan Review', 'B6.B', 'Review In Progress', 'b', 'Examination', 'permits.status', 'Examination', 'P4', 0.9, '—', '#E0E7FF', '🔍', '#E0E7FF', '🔍', '#E0E7FF', '🔍', 30),
  (32, 10, 'BP2', 'Plan Review', 'B6.C', 'Review Complete', 'a', 'Plan Review Complete', 'permits.status', 'Plan Review Complete', 'P3', 0.9, '—', '#E0E7FF', '🔍', '#E0E7FF', '🔍', '#E5E7EB', '🐛', 57),
  (33, 11, 'BP2', 'Plan Review', 'B6.C', 'Review Complete', 'b', 'Consultation Completed', 'permits.status', 'Consultation Completed', 'P4', 0.9, '—', '#E0E7FF', '🔍', '#E0E7FF', '🔍', '#E0E7FF', '🔍', 2),
  (34, 12, 'BP3', 'Notice & Response', 'B7.A', 'Notice Issued', 'a', 'Examiner''s Notice Sent', 'permits.status', 'Examiner''s Notice Sent', 'P4', 0.2, '↩ via #17 → #8 (re-queue)', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', NULL),
  (35, 13, 'BP3', 'Notice & Response', 'B7.A', 'Notice Issued', 'b', 'Notice Sent', 'permits.status', 'Notice Sent', 'UNMAPPED→null', 0.2, '↩ via #17 → #8 (re-queue)', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', 1),
  (36, 14, 'BP3', 'Notice & Response', 'B7.B', 'Deficiency Confirmed', 'a', 'Deficiency Notice', 'permits.status', 'Deficiency Notice Issued', 'P5', 0.2, '↩ via #17 → #8 (re-queue)', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', 117),
  (37, 15, 'BP3', 'Notice & Response', 'B7.C', 'Application Paused', 'a', 'On Hold', 'permits.status', 'Application On Hold', 'P5', 0.2, '↩ #17 (when applicant responds) or → #51 Cancelled (if abandoned)', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', '#FEF9C3', '⏸️', NULL),
  (38, 16, 'BP3', 'Notice & Response', 'B7.C', 'Application Paused', 'b', 'On Hold (variant)', 'permits.status', 'Application on Hold', 'P5', 0.2, '↩ #17 (when applicant responds) or → #51 Cancelled', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', '#FEF9C3', '⏸️', 4),
  (39, 17, 'BP3', 'Notice & Response', 'B7.D', 'Response Received', 'a', 'Response Received', 'permits.status', 'Response Received', 'P5', 0.4, '↩ #8 Under Review (re-queue)', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', 436),
  (40, 18, 'BP3', 'Notice & Response', 'B7.E', 'Cross-Folder Block', 'a', 'Parent Folder Pending', 'permits.status', 'Pending Parent Folder Review', 'P5', 0.2, '↩ #8 (when parent advances)', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', '#FEF3C7', '⚠️', 33),
  (41, 19, 'BP4', 'Pre-Issuance', 'B8.A', 'Permit Approved', 'a', 'Approved', 'permits.status', 'Approved', 'P6', 0.8, '—', '#CCFBF1', '📑', '#CCFBF1', '📑', '#CCFBF1', '📑', 23),
  (42, 20, 'BP4', 'Pre-Issuance', 'B8.B', 'Ready for Issuance', 'a', 'Ready for Issuance', 'permits.status', 'Ready for Issuance', 'P6', 0.8, '—', '#CCFBF1', '📑', '#CCFBF1', '📑', '#CCFBF1', '📑', 233),
  (43, 21, 'BP4', 'Pre-Issuance', 'B8.C', 'Outstanding Conditions', 'a', 'Forwarded for Issuance', 'permits.status', 'Forwarded for Issuance', 'P6', 0.7, '—', '#CCFBF1', '📑', '#CCFBF1', '📑', '#CCFBF1', '📑', 3),
  (44, 22, 'BP4', 'Pre-Issuance', 'B8.C', 'Outstanding Conditions', 'b', 'Issuance Pending', 'permits.status', 'Issuance Pending', 'P6', 0.7, '—', '#CCFBF1', '📑', '#CCFBF1', '📑', '#CCFBF1', '📑', NULL),
  (45, 23, 'BP4', 'Pre-Issuance', 'B8.C', 'Outstanding Conditions', 'c', 'Agreement in Progress', 'permits.status', 'Agreement in Progress', 'P6', 0.7, '—', '#CCFBF1', '📑', '#CCFBF1', '📑', '#CCFBF1', '📑', 10),
  (46, 24, 'BP4', 'Pre-Issuance', 'B8.D', 'Cross-Domain Issuance', 'a', 'Licence Issued', 'permits.status', 'Licence Issued', 'P6', 0.7, '—', '#CCFBF1', '📑', '#CCFBF1', '📑', '#CCFBF1', '📑', 4),
  (47, 25, 'BP5', 'Construction', 'B9.A', 'Newly Issued', 'a', 'Permit Issued', 'permits.status', 'Permit Issued', 'P7a/P7b/P7c (or P9-P17)', 0.6, '→ #31 Inspection (when inspections begin)', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', NULL),
  (48, 26, 'BP5', 'Construction', 'B9.B', 'No Construction Yet', 'a', 'Work Not Started', 'permits.status', 'Work Not Started', 'P7d', 0.6, '—', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', NULL),
  (49, 27, 'BP5', 'Construction', 'B9.B', 'No Construction Yet', 'b', 'Extension Granted', 'permits.status', 'Extension Granted', 'P7d', 0.6, '—', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', 3),
  (50, 31, 'BP5', 'Construction', 'B9.C', 'Active Inspection (status)', 'a', 'Inspection', 'permits.status', 'Inspection', 'P9-P17 (via stages 100-134) or P18', NULL, '→ stages #100-134', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', NULL),
  (51, 32, 'BP5', 'Construction', 'B9.C', 'Active Inspection (status)', 'b', 'Forward to Inspector', 'permits.status', 'Forward to Inspector', 'P18', NULL, '→ #31 Inspection', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', 1),
  (52, 33, 'BP5', 'Construction', 'B9.C', 'Active Inspection (status)', 'c', 'Rescheduled', 'permits.status', 'Rescheduled', 'P18', NULL, '→ #31 Inspection', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', '#FFEDD5', '🏗️', 1),
  (53, 100, 'I1', 'Site Prep & Foundations', 'B10.A', 'Site Prep', 'a', 'Site Grading', 'insp.stage', 'Site Grading Inspection', 'P9', NULL, '↩ same stage if `status=''Not Passed''` (re-inspection)', '#FEF3C7', '🪨', '#FEF3C7', '🪨', '#FEF3C7', '🪨', NULL),
  (54, 101, 'I1', 'Site Prep & Foundations', 'B10.A', 'Site Prep', 'b', 'Excavation/Shoring', 'insp.stage', 'Excavation/Shoring', 'P9', NULL, '↩ same stage if Not Passed', '#FEF3C7', '🪨', '#FEF3C7', '🪨', '#FEF3C7', '🪨', NULL),
  (55, 102, 'I1', 'Site Prep & Foundations', 'B10.A', 'Site Prep', 'c', 'Demolition', 'insp.stage', 'Demolition', 'P9', NULL, '↩ same stage if Not Passed', '#FEF3C7', '🪨', '#FEF3C7', '🪨', '#FEF3C7', '🪨', NULL),
  (56, 103, 'I1', 'Site Prep & Foundations', 'B10.B', 'Foundations', 'a', 'Footings/Foundations', 'insp.stage', 'Footings/Foundations', 'P10', NULL, '↩ same stage if Not Passed', '#FEF3C7', '🪨', '#FEF3C7', '🪨', '#FEF3C7', '🪨', NULL),
  (57, 104, 'I1', 'Site Prep & Foundations', 'B10.B', 'Foundations', 'b', 'Foundation', 'insp.stage', 'Foundation', 'P10', NULL, '↩ same stage if Not Passed', '#FEF3C7', '🪨', '#FEF3C7', '🪨', '#FEF3C7', '🪨', 2),
  (58, 105, 'I2', 'Structural & MEP', 'B11.A', 'Framing', 'a', 'Structural Framing', 'insp.stage', 'Structural Framing', 'P11', NULL, '↩ same stage if Not Passed', '#E0F2FE', '🔧', '#E0F2FE', '🔧', '#E0F2FE', '🔧', NULL),
  (59, 106, 'I2', 'Structural & MEP', 'B11.B', 'MEP Rough-in', 'a', 'HVAC Rough-in', 'insp.stage', 'HVAC/Extraction Rough-in', 'P12', NULL, '↩ same stage if Not Passed', '#E0F2FE', '🔧', '#E0F2FE', '🔧', '#E0F2FE', '🔧', 883),
  (60, 107, 'I2', 'Structural & MEP', 'B11.B', 'MEP Rough-in', 'b', 'Water Service', 'insp.stage', 'Water Service', 'P12', NULL, '↩ same stage if Not Passed', '#E0F2FE', '🔧', '#E0F2FE', '🔧', '#E0F2FE', '🔧', 888),
  (61, 108, 'I2', 'Structural & MEP', 'B11.B', 'MEP Rough-in', 'c', 'Water Distribution', 'insp.stage', 'Water Distribution', 'P12', NULL, '↩ same stage if Not Passed', '#E0F2FE', '🔧', '#E0F2FE', '🔧', '#E0F2FE', '🔧', 911),
  (62, 109, 'I2', 'Structural & MEP', 'B11.B', 'MEP Rough-in', 'd', 'Drain/Waste/Vents', 'insp.stage', 'Drain/Waste/Vents', 'P12', NULL, '↩ same stage if Not Passed', '#E0F2FE', '🔧', '#E0F2FE', '🔧', '#E0F2FE', '🔧', 910),
  (63, 110, 'I2', 'Structural & MEP', 'B11.B', 'MEP Rough-in', 'e', 'Sewers/Drains/Sewage', 'insp.stage', 'Sewers/Drains/Sewage System', 'P12', NULL, '↩ same stage if Not Passed', '#E0F2FE', '🔧', '#E0F2FE', '🔧', '#E0F2FE', '🔧', 890),
  (64, 111, 'I2', 'Structural & MEP', 'B11.B', 'MEP Rough-in', 'f', 'Fire Service', 'insp.stage', 'Fire Service', 'P12', NULL, '↩ same stage if Not Passed', '#E0F2FE', '🔧', '#E0F2FE', '🔧', '#E0F2FE', '🔧', 889),
  (65, 112, 'I2', 'Structural & MEP', 'B11.B', 'MEP Rough-in', 'g', 'Fire Access Routes', 'insp.stage', 'Fire Access Routes', 'P12', NULL, '↩ same stage if Not Passed', '#E0F2FE', '🔧', '#E0F2FE', '🔧', '#E0F2FE', '🔧', NULL),
  (66, 113, 'I2', 'Structural & MEP', 'B11.B', 'MEP Rough-in', 'h', 'Fire Protection Systems', 'insp.stage', 'Fire Protection Systems', 'P12', NULL, '↩ same stage if Not Passed', '#E0F2FE', '🔧', '#E0F2FE', '🔧', '#E0F2FE', '🔧', NULL),
  (67, 114, 'I3', 'Enclosure & Finishes', 'B12.A', 'Insulation', 'a', 'Insulation/Vapour Barrier', 'insp.stage', 'Insulation/Vapour Barrier', 'P13', NULL, '↩ same stage if Not Passed', '#D1FAE5', '🎨', '#D1FAE5', '🎨', '#D1FAE5', '🎨', NULL),
  (68, 115, 'I3', 'Enclosure & Finishes', 'B12.A', 'Insulation', 'b', 'Insulation', 'insp.stage', 'Insulation', 'P13', NULL, '↩ same stage if Not Passed', '#D1FAE5', '🎨', '#D1FAE5', '🎨', '#D1FAE5', '🎨', 1),
  (69, 116, 'I3', 'Enclosure & Finishes', 'B12.A', 'Insulation', 'c', 'Insulation & AirBarrier', 'insp.stage', 'Insulation & Vapour/AirBarrier Passed on', 'P13', NULL, '↩ same stage if Not Passed', '#D1FAE5', '🎨', '#D1FAE5', '🎨', '#D1FAE5', '🎨', 1),
  (70, 117, 'I3', 'Enclosure & Finishes', 'B12.B', 'Fire Sep', 'a', 'Fire Separations', 'insp.stage', 'Fire Separations', 'P14', NULL, '↩ same stage if Not Passed', '#D1FAE5', '🎨', '#D1FAE5', '🎨', '#D1FAE5', '🎨', NULL),
  (71, 118, 'I3', 'Enclosure & Finishes', 'B12.C', 'Interior Finals', 'a', 'Interior Final', 'insp.stage', 'Interior Final Inspection', 'P15', NULL, '↩ same stage if Not Passed', '#D1FAE5', '🎨', '#D1FAE5', '🎨', '#D1FAE5', '🎨', NULL),
  (72, 119, 'I3', 'Enclosure & Finishes', 'B12.C', 'Interior Finals', 'b', 'Plumbing Final', 'insp.stage', 'Plumbing Final', 'P15', NULL, '↩ same stage if Not Passed', '#D1FAE5', '🎨', '#D1FAE5', '🎨', '#D1FAE5', '🎨', 914),
  (73, 120, 'I3', 'Enclosure & Finishes', 'B12.C', 'Interior Finals', 'c', 'HVAC Final', 'insp.stage', 'HVAC Final', 'P15', NULL, '↩ same stage if Not Passed', '#D1FAE5', '🎨', '#D1FAE5', '🎨', '#D1FAE5', '🎨', 883),
  (74, 121, 'I3', 'Enclosure & Finishes', 'B12.D', 'Exterior Finals', 'a', 'Exterior Final', 'insp.stage', 'Exterior Final Inspection', 'P16', NULL, '↩ same stage if Not Passed', '#D1FAE5', '🎨', '#D1FAE5', '🎨', '#D1FAE5', '🎨', NULL),
  (75, 122, 'I4', 'Final / Specialty', 'B13.A', 'Project Final', 'a', 'Occupancy', 'insp.stage', 'Occupancy', 'P17', NULL, '(terminal)', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#DCFCE7', '✅', NULL),
  (76, 123, 'I4', 'Final / Specialty', 'B13.A', 'Project Final', 'b', 'Final Inspection', 'insp.stage', 'Final Inspection', 'P17', NULL, '(terminal)', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#DCFCE7', '✅', NULL),
  (77, 124, 'I4', 'Final / Specialty', 'B13.B', 'Specialty', 'a', 'Pool Suction/Gravity', 'insp.stage', 'Pool Suction/Gravity Outlets', 'UNMAPPED→P17 fallback', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', NULL),
  (78, 125, 'I4', 'Final / Specialty', 'B13.B', 'Specialty', 'b', 'Pool Circulation', 'insp.stage', 'Pool Circulation System', 'UNMAPPED→P17 fallback', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', NULL),
  (79, 126, 'I4', 'Final / Specialty', 'B13.B', 'Specialty', 'c', 'Repair/Retrofit', 'insp.stage', 'Repair/Retrofit', 'UNMAPPED→P17 fallback', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', NULL),
  (80, 127, 'I4', 'Final / Specialty', 'B13.B', 'Specialty', 'd', 'Change of Use', 'insp.stage', 'Change of Use', 'UNMAPPED→P17 fallback', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', NULL),
  (81, 128, 'I4', 'Final / Specialty', 'B13.B', 'Specialty', 'e', 'System', 'insp.stage', 'System', 'UNMAPPED→P17 fallback', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', NULL),
  (82, 129, 'I4', 'Final / Specialty', 'B13.B', 'Specialty', 'f', 'Security Device', 'insp.stage', 'Security Device', 'UNMAPPED→P17 fallback', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', NULL),
  (83, 130, 'I4', 'Final / Specialty', 'B13.B', 'Specialty', 'g', 'Tent/Portable Classroom', 'insp.stage', 'Tent/Portable Classroom', 'UNMAPPED→P17 fallback', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', NULL),
  (84, 131, 'I4', 'Final / Specialty', 'B13.C', 'Data-Quality Outliers', 'a', 'Final Interior', 'insp.stage', 'Final Interior', 'UNMAPPED→P17 fallback', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', 1),
  (85, 132, 'I4', 'Final / Specialty', 'B13.C', 'Data-Quality Outliers', 'b', 'HVAC Permit?', 'insp.stage', 'HVAC Permit?', 'P12', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', 1),
  (86, 133, 'I4', 'Final / Specialty', 'B13.C', 'Data-Quality Outliers', 'c', 'Survey', 'insp.stage', 'Survey', 'UNMAPPED→P17 fallback', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', 1),
  (87, 134, 'I4', 'Final / Specialty', 'B13.C', 'Data-Quality Outliers', 'd', 'Survey Submitted?', 'insp.stage', 'Survey Submitted?', 'UNMAPPED→P17 fallback', NULL, '—', '#FEF3C7', '🏆', '#FEF3C7', '🏆', '#E5E7EB', '🐛', 1),
  (88, 28, 'BP6', 'Revision', 'B14.A', 'Revision', 'a', 'Revision Issued', 'permits.status', 'Revision Issued', 'P8', 0.3, '↩ #8 (revision review)', '#F3E8FF', '🔄', '#F3E8FF', '🔄', '#F3E8FF', '🔄', NULL),
  (89, 29, 'BP6', 'Revision', 'B14.A', 'Revision', 'b', 'Revised', 'permits.status', 'Revised', 'P8', 0.3, '↩ #8 (revision review)', '#F3E8FF', '🔄', '#F3E8FF', '🔄', '#F3E8FF', '🔄', 27),
  (90, 30, 'BP6', 'Revision', 'B14.A', 'Revision', 'c', 'Order Complied', 'permits.status', 'Order Complied', 'P8', 0.3, '→ #31 Inspection', '#F3E8FF', '🔄', '#F3E8FF', '🔄', '#F3E8FF', '🔄', 22),
  (91, 34, 'BP7', 'Closure', 'B15.A', 'Wind-Down Cancellation', 'a', 'Pending Closed', 'permits.status', 'Pending Closed', 'P19', NULL, '→ #39 Closed', '#E2E8F0', '🏁', '#FEF3C7', '📅', '#FEF3C7', '📅', NULL),
  (92, 35, 'BP7', 'Closure', 'B15.A', 'Wind-Down Cancellation', 'b', 'Pending Cancellation', 'permits.status', 'Pending Cancellation', 'P19', NULL, '→ #51 Cancelled (if proceeds)', '#E2E8F0', '🏁', '#FEF3C7', '📅', '#FEF3C7', '📅', 488),
  (93, 38, 'BP7', 'Closure', 'B15.A', 'Wind-Down Cancellation', 'c', 'Inspection Request to Cancel', 'permits.status', 'Inspection Request to Cancel', 'P19', NULL, '→ #39 Closed', '#E2E8F0', '🏁', '#FEF3C7', '📅', '#FEF3C7', '📅', 1),
  (94, 36, 'BP7', 'Closure', 'B15.B', 'Wind-Down Revocation', 'a', 'Revocation Pending', 'permits.status', 'Revocation Pending', 'P19', NULL, '→ #49 Permit Revoked', '#E2E8F0', '🏁', '#FECACA', '🚫', '#FECACA', '🚫', NULL),
  (95, 37, 'BP7', 'Closure', 'B15.B', 'Wind-Down Revocation', 'b', 'Revocation Notice Sent', 'permits.status', 'Revocation Notice Sent', 'P19', NULL, '→ #49 Permit Revoked', '#E2E8F0', '🏁', '#FECACA', '🚫', '#FECACA', '🚫', 1),
  (96, 39, 'BP7', 'Closure', 'B15.C', 'Closed', 'a', 'Closed', 'permits.status', 'Closed', 'P20', NULL, '(terminal)', '#E2E8F0', '🏁', '#E2E8F0', '🏁', '#E2E8F0', '🏁', NULL),
  (97, 40, 'BP7', 'Closure', 'B15.C', 'Closed', 'b', 'File Closed', 'permits.status', 'File Closed', 'P20', NULL, '(terminal)', '#E2E8F0', '🏁', '#E2E8F0', '🏁', '#E2E8F0', '🏁', 6),
  (98, 41, 'BP7', 'Closure', 'B15.C', 'Closed', 'c', 'Permit Issued/Close File', 'permits.status', 'Permit Issued/Close File', 'P20', NULL, '(terminal)', '#E2E8F0', '🏁', '#E2E8F0', '🏁', '#E2E8F0', '🏁', 2),
  (99, 42, 'BP7', 'Closure', 'B15.D', 'Dead — Refusal', 'a', 'Refusal Notice', 'permits.status', 'Refusal Notice', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FECACA', '❌', '#FECACA', '❌', 958),
  (100, 52, 'BP7', 'Closure', 'B15.D', 'Dead — Refusal', 'b', 'Refused', 'permits.status', 'Refused', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FECACA', '❌', '#FECACA', '❌', 1),
  (101, 43, 'BP7', 'Closure', 'B15.E', 'Dead — Withdrawal', 'a', 'Abandoned', 'permits.status', 'Abandoned', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FEE2E2', '🗑️', '#FEE2E2', '🗑️', 122),
  (102, 44, 'BP7', 'Closure', 'B15.E', 'Dead — Withdrawal', 'b', 'Application Withdrawn', 'permits.status', 'Application Withdrawn', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FEE2E2', '🗑️', '#FEE2E2', '🗑️', 49),
  (103, 47, 'BP7', 'Closure', 'B15.E', 'Dead — Withdrawal', 'c', 'Not Accepted', 'permits.status', 'Not Accepted', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FEE2E2', '🗑️', '#FEE2E2', '🗑️', 9),
  (104, 49, 'BP7', 'Closure', 'B15.F', 'Dead — Revocation', 'a', 'Permit Revoked', 'permits.status', 'Permit Revoked', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FECACA', '🚫', '#FECACA', '🚫', 2),
  (105, 50, 'BP7', 'Closure', 'B15.F', 'Dead — Revocation', 'b', 'Revoked', 'permits.status', 'Revoked', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FECACA', '🚫', '#FECACA', '🚫', 2),
  (106, 45, 'BP7', 'Closure', 'B15.G', 'Dead — Enforcement', 'a', 'Work Suspended', 'permits.status', 'Work Suspended', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FECACA', '⛔', '#FECACA', '⛔', 18),
  (107, 46, 'BP7', 'Closure', 'B15.G', 'Dead — Enforcement', 'b', 'VIOLATION', 'permits.status', 'VIOLATION', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FECACA', '⛔', '#FECACA', '⛔', 16),
  (108, 48, 'BP7', 'Closure', 'B15.G', 'Dead — Enforcement', 'c', 'Order Issued', 'permits.status', 'Order Issued', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FECACA', '⛔', '#FECACA', '⛔', 7),
  (109, 51, 'BP7', 'Closure', 'B15.H', 'Dead — Other', 'a', 'Cancelled', 'permits.status', 'Cancelled', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FEE2E2', '🗑️', '#FEE2E2', '🗑️', 1),
  (110, 53, 'BP7', 'Closure', 'B15.H', 'Dead — Other', 'b', 'Follow-up Required', 'permits.status', 'Follow-up Required', 'null (DEAD)', NULL, '(terminal)', '#E2E8F0', '🏁', '#FEE2E2', '🗑️', '#FEE2E2', '🗑️', 1)
ON CONFLICT (seq) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════
-- DOWN — manual rollback only, intentionally not transactional
-- (Rule 6 / commit 8b1c10b)
-- ═══════════════════════════════════════════════════════════════════
-- Reverting this migration empties the catalog. The table from migration
-- 128 remains; the Phase E classifier cannot derive granular columns
-- against an empty catalog. Migration 131 (signals seed) would be
-- left dangling (its rows FK to catalog.seq, which would then be empty —
-- rows survive but reference no parent until catalog is re-seeded).
--
-- To roll back manually:
--
--   DELETE FROM universal_stream_catalog;
--
-- Re-running migration 129 restores the 110 rows.
