-- 136: Phase B logic_variables seed — seq-level distribution bands +
-- CoA CRM thresholds + Phase B operator-tunable defaults.
--
-- Consumed by:
--   * Phase E `assert-lifecycle-phase-distribution.js` — reads
--     `lifecycle_band_seq_<N>_min/max` + `_sample_size_threshold` per
--     Spec 42 §6.7 step 4 (seq-level distribution gate replacing the
--     legacy P-code bands).
--   * Phase F `update-tracked-projects.js` — reads CoA stall + imminent
--     thresholds per Spec 82.
--   * Phase B `lead-id-orphan-audit.infra.test.ts` (R5.5 follow-up) —
--     reads `coa_orphan_lead_id_warn_threshold`.
--
-- All 330 seq-band values land NULL by design — Phase E iterative
-- recalibration on a staging copy of full CKAN data sets the real
-- min/max/threshold values per seq once the classifier is wired and the
-- distribution shape is observable. The standalone CoA / retention /
-- orphan / preflight keys carry Spec-aligned defaults that can be tuned
-- via /admin/control-panel per Spec 86 §1.
--
-- ON CONFLICT (variable_key) DO NOTHING: re-runs are no-ops, and any
-- operator-tuned values already present in the DB are preserved
-- (consistent with migration 119 + 121 pattern).

-- ═══════════════════════════════════════════════════════════════════
-- UP
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO logic_variables (variable_key, variable_value, description) VALUES
  ('lifecycle_band_seq_1_min', NULL, 'Min row-count band for seq 1 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_1_max', NULL, 'Max row-count band for seq 1 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_1_sample_size_threshold', NULL, 'Tier selector for seq 1: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_2_min', NULL, 'Min row-count band for seq 2 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_2_max', NULL, 'Max row-count band for seq 2 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_2_sample_size_threshold', NULL, 'Tier selector for seq 2: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_3_min', NULL, 'Min row-count band for seq 3 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_3_max', NULL, 'Max row-count band for seq 3 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_3_sample_size_threshold', NULL, 'Tier selector for seq 3: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_4_min', NULL, 'Min row-count band for seq 4 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_4_max', NULL, 'Max row-count band for seq 4 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_4_sample_size_threshold', NULL, 'Tier selector for seq 4: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_5_min', NULL, 'Min row-count band for seq 5 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_5_max', NULL, 'Max row-count band for seq 5 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_5_sample_size_threshold', NULL, 'Tier selector for seq 5: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_6_min', NULL, 'Min row-count band for seq 6 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_6_max', NULL, 'Max row-count band for seq 6 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_6_sample_size_threshold', NULL, 'Tier selector for seq 6: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_7_min', NULL, 'Min row-count band for seq 7 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_7_max', NULL, 'Max row-count band for seq 7 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_7_sample_size_threshold', NULL, 'Tier selector for seq 7: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_8_min', NULL, 'Min row-count band for seq 8 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_8_max', NULL, 'Max row-count band for seq 8 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_8_sample_size_threshold', NULL, 'Tier selector for seq 8: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_9_min', NULL, 'Min row-count band for seq 9 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_9_max', NULL, 'Max row-count band for seq 9 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_9_sample_size_threshold', NULL, 'Tier selector for seq 9: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_10_min', NULL, 'Min row-count band for seq 10 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_10_max', NULL, 'Max row-count band for seq 10 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_10_sample_size_threshold', NULL, 'Tier selector for seq 10: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_11_min', NULL, 'Min row-count band for seq 11 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_11_max', NULL, 'Max row-count band for seq 11 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_11_sample_size_threshold', NULL, 'Tier selector for seq 11: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_12_min', NULL, 'Min row-count band for seq 12 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_12_max', NULL, 'Max row-count band for seq 12 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_12_sample_size_threshold', NULL, 'Tier selector for seq 12: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_13_min', NULL, 'Min row-count band for seq 13 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_13_max', NULL, 'Max row-count band for seq 13 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_13_sample_size_threshold', NULL, 'Tier selector for seq 13: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_14_min', NULL, 'Min row-count band for seq 14 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_14_max', NULL, 'Max row-count band for seq 14 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_14_sample_size_threshold', NULL, 'Tier selector for seq 14: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_15_min', NULL, 'Min row-count band for seq 15 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_15_max', NULL, 'Max row-count band for seq 15 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_15_sample_size_threshold', NULL, 'Tier selector for seq 15: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_16_min', NULL, 'Min row-count band for seq 16 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_16_max', NULL, 'Max row-count band for seq 16 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_16_sample_size_threshold', NULL, 'Tier selector for seq 16: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_17_min', NULL, 'Min row-count band for seq 17 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_17_max', NULL, 'Max row-count band for seq 17 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_17_sample_size_threshold', NULL, 'Tier selector for seq 17: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_18_min', NULL, 'Min row-count band for seq 18 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_18_max', NULL, 'Max row-count band for seq 18 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_18_sample_size_threshold', NULL, 'Tier selector for seq 18: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_19_min', NULL, 'Min row-count band for seq 19 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_19_max', NULL, 'Max row-count band for seq 19 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_19_sample_size_threshold', NULL, 'Tier selector for seq 19: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_20_min', NULL, 'Min row-count band for seq 20 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_20_max', NULL, 'Max row-count band for seq 20 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_20_sample_size_threshold', NULL, 'Tier selector for seq 20: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_21_min', NULL, 'Min row-count band for seq 21 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_21_max', NULL, 'Max row-count band for seq 21 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_21_sample_size_threshold', NULL, 'Tier selector for seq 21: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_22_min', NULL, 'Min row-count band for seq 22 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_22_max', NULL, 'Max row-count band for seq 22 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_22_sample_size_threshold', NULL, 'Tier selector for seq 22: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_23_min', NULL, 'Min row-count band for seq 23 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_23_max', NULL, 'Max row-count band for seq 23 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_23_sample_size_threshold', NULL, 'Tier selector for seq 23: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_24_min', NULL, 'Min row-count band for seq 24 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_24_max', NULL, 'Max row-count band for seq 24 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_24_sample_size_threshold', NULL, 'Tier selector for seq 24: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_25_min', NULL, 'Min row-count band for seq 25 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_25_max', NULL, 'Max row-count band for seq 25 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_25_sample_size_threshold', NULL, 'Tier selector for seq 25: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_26_min', NULL, 'Min row-count band for seq 26 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_26_max', NULL, 'Max row-count band for seq 26 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_26_sample_size_threshold', NULL, 'Tier selector for seq 26: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_27_min', NULL, 'Min row-count band for seq 27 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_27_max', NULL, 'Max row-count band for seq 27 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_27_sample_size_threshold', NULL, 'Tier selector for seq 27: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_28_min', NULL, 'Min row-count band for seq 28 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_28_max', NULL, 'Max row-count band for seq 28 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_28_sample_size_threshold', NULL, 'Tier selector for seq 28: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_29_min', NULL, 'Min row-count band for seq 29 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_29_max', NULL, 'Max row-count band for seq 29 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_29_sample_size_threshold', NULL, 'Tier selector for seq 29: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_30_min', NULL, 'Min row-count band for seq 30 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_30_max', NULL, 'Max row-count band for seq 30 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_30_sample_size_threshold', NULL, 'Tier selector for seq 30: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_31_min', NULL, 'Min row-count band for seq 31 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_31_max', NULL, 'Max row-count band for seq 31 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_31_sample_size_threshold', NULL, 'Tier selector for seq 31: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_32_min', NULL, 'Min row-count band for seq 32 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_32_max', NULL, 'Max row-count band for seq 32 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_32_sample_size_threshold', NULL, 'Tier selector for seq 32: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_33_min', NULL, 'Min row-count band for seq 33 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_33_max', NULL, 'Max row-count band for seq 33 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_33_sample_size_threshold', NULL, 'Tier selector for seq 33: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_34_min', NULL, 'Min row-count band for seq 34 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_34_max', NULL, 'Max row-count band for seq 34 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_34_sample_size_threshold', NULL, 'Tier selector for seq 34: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_35_min', NULL, 'Min row-count band for seq 35 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_35_max', NULL, 'Max row-count band for seq 35 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_35_sample_size_threshold', NULL, 'Tier selector for seq 35: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_36_min', NULL, 'Min row-count band for seq 36 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_36_max', NULL, 'Max row-count band for seq 36 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_36_sample_size_threshold', NULL, 'Tier selector for seq 36: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_37_min', NULL, 'Min row-count band for seq 37 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_37_max', NULL, 'Max row-count band for seq 37 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_37_sample_size_threshold', NULL, 'Tier selector for seq 37: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_38_min', NULL, 'Min row-count band for seq 38 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_38_max', NULL, 'Max row-count band for seq 38 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_38_sample_size_threshold', NULL, 'Tier selector for seq 38: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_39_min', NULL, 'Min row-count band for seq 39 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_39_max', NULL, 'Max row-count band for seq 39 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_39_sample_size_threshold', NULL, 'Tier selector for seq 39: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_40_min', NULL, 'Min row-count band for seq 40 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_40_max', NULL, 'Max row-count band for seq 40 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_40_sample_size_threshold', NULL, 'Tier selector for seq 40: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_41_min', NULL, 'Min row-count band for seq 41 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_41_max', NULL, 'Max row-count band for seq 41 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_41_sample_size_threshold', NULL, 'Tier selector for seq 41: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_42_min', NULL, 'Min row-count band for seq 42 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_42_max', NULL, 'Max row-count band for seq 42 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_42_sample_size_threshold', NULL, 'Tier selector for seq 42: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_43_min', NULL, 'Min row-count band for seq 43 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_43_max', NULL, 'Max row-count band for seq 43 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_43_sample_size_threshold', NULL, 'Tier selector for seq 43: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_44_min', NULL, 'Min row-count band for seq 44 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_44_max', NULL, 'Max row-count band for seq 44 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_44_sample_size_threshold', NULL, 'Tier selector for seq 44: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_45_min', NULL, 'Min row-count band for seq 45 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_45_max', NULL, 'Max row-count band for seq 45 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_45_sample_size_threshold', NULL, 'Tier selector for seq 45: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_46_min', NULL, 'Min row-count band for seq 46 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_46_max', NULL, 'Max row-count band for seq 46 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_46_sample_size_threshold', NULL, 'Tier selector for seq 46: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_47_min', NULL, 'Min row-count band for seq 47 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_47_max', NULL, 'Max row-count band for seq 47 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_47_sample_size_threshold', NULL, 'Tier selector for seq 47: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_48_min', NULL, 'Min row-count band for seq 48 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_48_max', NULL, 'Max row-count band for seq 48 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_48_sample_size_threshold', NULL, 'Tier selector for seq 48: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_49_min', NULL, 'Min row-count band for seq 49 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_49_max', NULL, 'Max row-count band for seq 49 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_49_sample_size_threshold', NULL, 'Tier selector for seq 49: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_50_min', NULL, 'Min row-count band for seq 50 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_50_max', NULL, 'Max row-count band for seq 50 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_50_sample_size_threshold', NULL, 'Tier selector for seq 50: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_51_min', NULL, 'Min row-count band for seq 51 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_51_max', NULL, 'Max row-count band for seq 51 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_51_sample_size_threshold', NULL, 'Tier selector for seq 51: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_52_min', NULL, 'Min row-count band for seq 52 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_52_max', NULL, 'Max row-count band for seq 52 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_52_sample_size_threshold', NULL, 'Tier selector for seq 52: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_53_min', NULL, 'Min row-count band for seq 53 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_53_max', NULL, 'Max row-count band for seq 53 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_53_sample_size_threshold', NULL, 'Tier selector for seq 53: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_54_min', NULL, 'Min row-count band for seq 54 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_54_max', NULL, 'Max row-count band for seq 54 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_54_sample_size_threshold', NULL, 'Tier selector for seq 54: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_55_min', NULL, 'Min row-count band for seq 55 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_55_max', NULL, 'Max row-count band for seq 55 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_55_sample_size_threshold', NULL, 'Tier selector for seq 55: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_56_min', NULL, 'Min row-count band for seq 56 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_56_max', NULL, 'Max row-count band for seq 56 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_56_sample_size_threshold', NULL, 'Tier selector for seq 56: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_57_min', NULL, 'Min row-count band for seq 57 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_57_max', NULL, 'Max row-count band for seq 57 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_57_sample_size_threshold', NULL, 'Tier selector for seq 57: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_58_min', NULL, 'Min row-count band for seq 58 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_58_max', NULL, 'Max row-count band for seq 58 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_58_sample_size_threshold', NULL, 'Tier selector for seq 58: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_59_min', NULL, 'Min row-count band for seq 59 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_59_max', NULL, 'Max row-count band for seq 59 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_59_sample_size_threshold', NULL, 'Tier selector for seq 59: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_60_min', NULL, 'Min row-count band for seq 60 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_60_max', NULL, 'Max row-count band for seq 60 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_60_sample_size_threshold', NULL, 'Tier selector for seq 60: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_61_min', NULL, 'Min row-count band for seq 61 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_61_max', NULL, 'Max row-count band for seq 61 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_61_sample_size_threshold', NULL, 'Tier selector for seq 61: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_62_min', NULL, 'Min row-count band for seq 62 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_62_max', NULL, 'Max row-count band for seq 62 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_62_sample_size_threshold', NULL, 'Tier selector for seq 62: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_63_min', NULL, 'Min row-count band for seq 63 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_63_max', NULL, 'Max row-count band for seq 63 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_63_sample_size_threshold', NULL, 'Tier selector for seq 63: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_64_min', NULL, 'Min row-count band for seq 64 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_64_max', NULL, 'Max row-count band for seq 64 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_64_sample_size_threshold', NULL, 'Tier selector for seq 64: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_65_min', NULL, 'Min row-count band for seq 65 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_65_max', NULL, 'Max row-count band for seq 65 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_65_sample_size_threshold', NULL, 'Tier selector for seq 65: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_66_min', NULL, 'Min row-count band for seq 66 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_66_max', NULL, 'Max row-count band for seq 66 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_66_sample_size_threshold', NULL, 'Tier selector for seq 66: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_67_min', NULL, 'Min row-count band for seq 67 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_67_max', NULL, 'Max row-count band for seq 67 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_67_sample_size_threshold', NULL, 'Tier selector for seq 67: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_68_min', NULL, 'Min row-count band for seq 68 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_68_max', NULL, 'Max row-count band for seq 68 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_68_sample_size_threshold', NULL, 'Tier selector for seq 68: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_69_min', NULL, 'Min row-count band for seq 69 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_69_max', NULL, 'Max row-count band for seq 69 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_69_sample_size_threshold', NULL, 'Tier selector for seq 69: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_70_min', NULL, 'Min row-count band for seq 70 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_70_max', NULL, 'Max row-count band for seq 70 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_70_sample_size_threshold', NULL, 'Tier selector for seq 70: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_71_min', NULL, 'Min row-count band for seq 71 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_71_max', NULL, 'Max row-count band for seq 71 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_71_sample_size_threshold', NULL, 'Tier selector for seq 71: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_72_min', NULL, 'Min row-count band for seq 72 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_72_max', NULL, 'Max row-count band for seq 72 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_72_sample_size_threshold', NULL, 'Tier selector for seq 72: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_73_min', NULL, 'Min row-count band for seq 73 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_73_max', NULL, 'Max row-count band for seq 73 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_73_sample_size_threshold', NULL, 'Tier selector for seq 73: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_74_min', NULL, 'Min row-count band for seq 74 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_74_max', NULL, 'Max row-count band for seq 74 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_74_sample_size_threshold', NULL, 'Tier selector for seq 74: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_75_min', NULL, 'Min row-count band for seq 75 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_75_max', NULL, 'Max row-count band for seq 75 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_75_sample_size_threshold', NULL, 'Tier selector for seq 75: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_76_min', NULL, 'Min row-count band for seq 76 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_76_max', NULL, 'Max row-count band for seq 76 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_76_sample_size_threshold', NULL, 'Tier selector for seq 76: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_77_min', NULL, 'Min row-count band for seq 77 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_77_max', NULL, 'Max row-count band for seq 77 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_77_sample_size_threshold', NULL, 'Tier selector for seq 77: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_78_min', NULL, 'Min row-count band for seq 78 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_78_max', NULL, 'Max row-count band for seq 78 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_78_sample_size_threshold', NULL, 'Tier selector for seq 78: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_79_min', NULL, 'Min row-count band for seq 79 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_79_max', NULL, 'Max row-count band for seq 79 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_79_sample_size_threshold', NULL, 'Tier selector for seq 79: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_80_min', NULL, 'Min row-count band for seq 80 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_80_max', NULL, 'Max row-count band for seq 80 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_80_sample_size_threshold', NULL, 'Tier selector for seq 80: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_81_min', NULL, 'Min row-count band for seq 81 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_81_max', NULL, 'Max row-count band for seq 81 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_81_sample_size_threshold', NULL, 'Tier selector for seq 81: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_82_min', NULL, 'Min row-count band for seq 82 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_82_max', NULL, 'Max row-count band for seq 82 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_82_sample_size_threshold', NULL, 'Tier selector for seq 82: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_83_min', NULL, 'Min row-count band for seq 83 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_83_max', NULL, 'Max row-count band for seq 83 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_83_sample_size_threshold', NULL, 'Tier selector for seq 83: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_84_min', NULL, 'Min row-count band for seq 84 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_84_max', NULL, 'Max row-count band for seq 84 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_84_sample_size_threshold', NULL, 'Tier selector for seq 84: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_85_min', NULL, 'Min row-count band for seq 85 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_85_max', NULL, 'Max row-count band for seq 85 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_85_sample_size_threshold', NULL, 'Tier selector for seq 85: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_86_min', NULL, 'Min row-count band for seq 86 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_86_max', NULL, 'Max row-count band for seq 86 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_86_sample_size_threshold', NULL, 'Tier selector for seq 86: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_87_min', NULL, 'Min row-count band for seq 87 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_87_max', NULL, 'Max row-count band for seq 87 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_87_sample_size_threshold', NULL, 'Tier selector for seq 87: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_88_min', NULL, 'Min row-count band for seq 88 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_88_max', NULL, 'Max row-count band for seq 88 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_88_sample_size_threshold', NULL, 'Tier selector for seq 88: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_89_min', NULL, 'Min row-count band for seq 89 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_89_max', NULL, 'Max row-count band for seq 89 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_89_sample_size_threshold', NULL, 'Tier selector for seq 89: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_90_min', NULL, 'Min row-count band for seq 90 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_90_max', NULL, 'Max row-count band for seq 90 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_90_sample_size_threshold', NULL, 'Tier selector for seq 90: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_91_min', NULL, 'Min row-count band for seq 91 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_91_max', NULL, 'Max row-count band for seq 91 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_91_sample_size_threshold', NULL, 'Tier selector for seq 91: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_92_min', NULL, 'Min row-count band for seq 92 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_92_max', NULL, 'Max row-count band for seq 92 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_92_sample_size_threshold', NULL, 'Tier selector for seq 92: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_93_min', NULL, 'Min row-count band for seq 93 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_93_max', NULL, 'Max row-count band for seq 93 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_93_sample_size_threshold', NULL, 'Tier selector for seq 93: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_94_min', NULL, 'Min row-count band for seq 94 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_94_max', NULL, 'Max row-count band for seq 94 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_94_sample_size_threshold', NULL, 'Tier selector for seq 94: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_95_min', NULL, 'Min row-count band for seq 95 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_95_max', NULL, 'Max row-count band for seq 95 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_95_sample_size_threshold', NULL, 'Tier selector for seq 95: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_96_min', NULL, 'Min row-count band for seq 96 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_96_max', NULL, 'Max row-count band for seq 96 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_96_sample_size_threshold', NULL, 'Tier selector for seq 96: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_97_min', NULL, 'Min row-count band for seq 97 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_97_max', NULL, 'Max row-count band for seq 97 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_97_sample_size_threshold', NULL, 'Tier selector for seq 97: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_98_min', NULL, 'Min row-count band for seq 98 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_98_max', NULL, 'Max row-count band for seq 98 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_98_sample_size_threshold', NULL, 'Tier selector for seq 98: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_99_min', NULL, 'Min row-count band for seq 99 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_99_max', NULL, 'Max row-count band for seq 99 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_99_sample_size_threshold', NULL, 'Tier selector for seq 99: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_100_min', NULL, 'Min row-count band for seq 100 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_100_max', NULL, 'Max row-count band for seq 100 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_100_sample_size_threshold', NULL, 'Tier selector for seq 100: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_101_min', NULL, 'Min row-count band for seq 101 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_101_max', NULL, 'Max row-count band for seq 101 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_101_sample_size_threshold', NULL, 'Tier selector for seq 101: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_102_min', NULL, 'Min row-count band for seq 102 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_102_max', NULL, 'Max row-count band for seq 102 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_102_sample_size_threshold', NULL, 'Tier selector for seq 102: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_103_min', NULL, 'Min row-count band for seq 103 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_103_max', NULL, 'Max row-count band for seq 103 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_103_sample_size_threshold', NULL, 'Tier selector for seq 103: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_104_min', NULL, 'Min row-count band for seq 104 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_104_max', NULL, 'Max row-count band for seq 104 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_104_sample_size_threshold', NULL, 'Tier selector for seq 104: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_105_min', NULL, 'Min row-count band for seq 105 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_105_max', NULL, 'Max row-count band for seq 105 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_105_sample_size_threshold', NULL, 'Tier selector for seq 105: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_106_min', NULL, 'Min row-count band for seq 106 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_106_max', NULL, 'Max row-count band for seq 106 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_106_sample_size_threshold', NULL, 'Tier selector for seq 106: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_107_min', NULL, 'Min row-count band for seq 107 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_107_max', NULL, 'Max row-count band for seq 107 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_107_sample_size_threshold', NULL, 'Tier selector for seq 107: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_108_min', NULL, 'Min row-count band for seq 108 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_108_max', NULL, 'Max row-count band for seq 108 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_108_sample_size_threshold', NULL, 'Tier selector for seq 108: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_109_min', NULL, 'Min row-count band for seq 109 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_109_max', NULL, 'Max row-count band for seq 109 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_109_sample_size_threshold', NULL, 'Tier selector for seq 109: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_band_seq_110_min', NULL, 'Min row-count band for seq 110 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_110_max', NULL, 'Max row-count band for seq 110 — populated by Phase E recalibration'),
  ('lifecycle_band_seq_110_sample_size_threshold', NULL, 'Tier selector for seq 110: tight|moderate|loose|info_only — auto-derived in Phase E'),
  ('lifecycle_status_history_retention_days', '1825', 'Default 5 years per Spec 86 §1; lifecycle_status_history rows older than this can be archived'),
  ('coa_stall_threshold_p2_days', '90', 'Per Spec 82 — CoA at Hearing Scheduled status this many days fires a stall alert'),
  ('coa_imminent_window_days', '7', 'Per Spec 82 — CoA hearing_date within this many days fires imminent-alert'),
  ('coa_orphan_lead_id_warn_threshold', '0', 'Spec 42 §6.6.A.1 CQA gate — lead_id_orphan_audit row count must be 0; >0 = FAIL'),
  ('phase_b_revision_num_max_length', '2', 'Phase B preflight — MAX(LENGTH(revision_num)) on permits; surface for review if exceeded')
ON CONFLICT (variable_key) DO NOTHING;

-- ═══════════════════════════════════════════════════════════════════
-- DOWN — manual rollback only, intentionally not transactional
-- (Rule 6 / commit 8b1c10b)
-- ═══════════════════════════════════════════════════════════════════
-- Reverting this migration removes the 335 new logic_variables rows.
-- Phase E distribution gate, Phase F CoA CRM alerts, and Phase B
-- preflight all lose their configuration anchors.
--
-- To roll back manually, enumerate each key explicitly (NEVER use a
-- wildcard DELETE — it would catch operator-added rows):
--
--   DELETE FROM logic_variables WHERE variable_key IN (
--     'lifecycle_band_seq_1_min',  'lifecycle_band_seq_1_max',  'lifecycle_band_seq_1_sample_size_threshold',
--     'lifecycle_band_seq_2_min',  'lifecycle_band_seq_2_max',  'lifecycle_band_seq_2_sample_size_threshold',
--     -- ... seqs 3-109 ...
--     'lifecycle_band_seq_110_min','lifecycle_band_seq_110_max','lifecycle_band_seq_110_sample_size_threshold',
--     'lifecycle_status_history_retention_days',
--     'coa_stall_threshold_p2_days',
--     'coa_imminent_window_days',
--     'coa_orphan_lead_id_warn_threshold',
--     'phase_b_revision_num_max_length'
--   );
