'use client';
/**
 * GlobalConfigCard — renders every numeric logic_variables key grouped by
 * domain (single render path — GROUPS, generated from the seed's declared
 * `admin.group` field; WF2 ADMIN-1 ratchet batch 5 retired the bespoke
 * lifecycle_seq_band_* section in favour of this ONE path), plus
 * income_premium_tiers (JSONB type, seeded via migration 097). Uses
 * DeltaGuardInput for numeric fields and JsonTiersEditor for the
 * income_premium_tiers JSONB field.
 *
 * SPEC LINK: docs/specs/02-web-admin/86_control_panel.md §5 Phase 3
 * SPEC LINK: docs/specs/01-pipeline/84_lifecycle_phase_engine.md §3.4
 * SPEC LINK: docs/specs/01-pipeline/124_step_standard_policy.md (Rule 3, "the admin intersection")
 */

import type { LogicVariableRow } from '@/lib/admin/control-panel';
import { DeltaGuardInput } from './DeltaGuardInput';
import { JsonTiersEditor } from './JsonTiersEditor';
import { useAdminControlsStore } from '../store/useAdminControlsStore';
import GENERATED_GROUPS from '../generated/logic-variable-groups.json';

/**
 * Logical groups for display — covers all numeric keys + income_premium_tiers.
 *
 * DERIVED (WF2 "Admin Tunable Coverage" commit 3) from
 * src/features/admin-controls/generated/logic-variable-groups.json, itself
 * generated by scripts/generate-logic-variable-groups.mjs (`npm run
 * logic-var-groups`) from the seed's declared `admin.group` field
 * (scripts/seeds/logic_variables.json) — a key's presence here is no longer
 * a hand-maintained fact that can silently drift from the seed; it is a
 * direct consequence of that key's own `admin` declaration. STATIC IMPORT,
 * no runtime fetch — the JSON is bundled at build time like any other
 * import, so this card's render behaviour and layout are unchanged.
 *
 * EXPORTED for the reconciliation test in src/tests/control-panel.logic.test.ts,
 * which asserts: all GROUPS numeric keys (excluding JSON_KEYS) ⊆ logic_variables.json.
 */
export const GROUPS: Array<{ label: string; keys: string[] }> = GENERATED_GROUPS;
/** EXPORTED for reconciliation test — keys rendered via JsonTiersEditor, not DeltaGuardInput. */
export const JSON_KEYS = new Set(['income_premium_tiers']);

/**
 * Number of digits after the decimal point in a finite number's own decimal
 * literal representation (`0.05` → 2, `14.5` → 1, `10000` → 0). Capped at 4
 * — these are hand-authored seed defaults, never a computed float with a
 * long tail — so a `toString()` round-trip is safe (no scientific notation
 * for anything in this magnitude range).
 */
export function decimalPlaces(n: number): number {
  if (!Number.isFinite(n)) return 0;
  const s = Math.abs(n).toString();
  if (s.includes('e') || s.includes('E')) return 0;
  const idx = s.indexOf('.');
  return idx === -1 ? 0 : Math.min(s.length - idx - 1, 4);
}

/**
 * Returns an appropriate input step for a given logic_variable key/value pair.
 * Large-magnitude keys (costs, durations in ms) get coarser steps; ratios/
 * confidence scores get fine steps.
 *
 * WF2 ADMIN-1 ratchet, F-4: `LogicVariableRow` carries only the live `value`
 * (no `min`/`max` — the seed's declared bounds are not plumbed to the admin
 * API today), so this derives from the CURRENTLY DISPLAYED value's own
 * decimal places rather than the name-pattern heuristic alone. A step
 * derived this way is guaranteed valid for the value it was derived from
 * (`value % step === 0` by construction), closing the HTML5 `stepMismatch`
 * class of bug the name-only heuristic could not see (e.g.
 * `archetype_t1_fsi_min` default `0.05` matched no ratio-name pattern and
 * fell through to the integer default `step={1}`). The name-pattern
 * fallback stays for the case a ratio-shaped key's CURRENT value happens to
 * be a whole number (e.g. exactly `1`) — decimals(1) === 0 would otherwise
 * derive `step={1}` on a 0-1 ratio field that should stay fine-grained.
 */
export function stepFor(key: string, value: number): number {
  if (key === 'cost_outlier_ceiling_cad') return 1_000_000;
  if (key === 'los_base_divisor' || key === 'scraper_latency_p50_warn_ms') return 100;
  if (key === 'placeholder_cost_threshold') return 100;
  // These keys contain "threshold" but are integer day/sqm/percentage values — NOT ratios.
  if (
    key === 'expired_threshold_days' ||
    key === 'coa_stall_threshold' ||
    key === 'massing_shed_threshold_sqm' ||
    key === 'scrape_early_phase_threshold_pct'
  ) return 1;
  // Lifecycle band/threshold keys are integer row counts, not ratios.
  // Must short-circuit BEFORE the decimal-derivation/name-pattern checks
  // below (which would otherwise derive a fractional step for counts in
  // the thousands, or for a count that happens to be a round number).
  if (key.startsWith('lifecycle_band_') || key.startsWith('lifecycle_cross_') || key.startsWith('lifecycle_seq_band_')) return 1;

  const decimals = decimalPlaces(value);
  if (decimals > 0) return Number((10 ** -decimals).toFixed(decimals));

  if (
    key.endsWith('_conf') ||
    key.endsWith('_conf_high') ||
    key.endsWith('_conf_medium') ||
    key.includes('confidence') ||
    key.includes('coverage_ratio') ||
    key.includes('threshold_pct') ||
    key.includes('_threshold') ||
    key.includes('fuzzy_match_threshold') ||
    key.includes('multiplier')
  ) return 0.01;
  return 1;
}

interface GlobalConfigCardProps {
  variables: LogicVariableRow[];
}

export function GlobalConfigCard({ variables }: GlobalConfigCardProps) {
  const updateDraftLogicVar = useAdminControlsStore((s) => s.updateDraftLogicVar);

  const byKey = new Map(variables.map((v) => [v.key, v]));

  return (
    <div className="space-y-6">
      {GROUPS.map((group) => {
        // WF2 ADMIN-1 ratchet, F-2: the retired bespoke seq-band section
        // suppressed itself entirely when no member rows were loaded
        // (`seqBandSeqs.length > 0 && (...)`); GROUPS never had that guard,
        // so a group with zero rows present in `variables` renders an empty
        // heading with no fields underneath. Restore the suppression at the
        // GROUPS level, generically, for every group — not just the one the
        // deletion happened to affect.
        if (!group.keys.some((k) => byKey.has(k))) return null;
        return (
          <section key={group.label}>
            <h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-gray-400 border-b border-gray-100 pb-1">
              {group.label}
            </h3>
            <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3">
              {group.keys.map((key) => {
                const row = byKey.get(key);
                if (!row) return null;

                if (JSON_KEYS.has(key)) {
                  return (
                    <div key={key} className="sm:col-span-2 lg:col-span-3">
                      <JsonTiersEditor
                        value={row.jsonValue}
                        onChange={(val) => updateDraftLogicVar(key, null, val)}
                      />
                    </div>
                  );
                }

                return (
                  <div key={key} className="pt-5">
                    <label className="block text-xs font-medium text-gray-500 uppercase tracking-wide mb-1">
                      {key}
                      {row.description && (
                        <span className="ml-1 text-gray-400 normal-case font-normal">
                          — {row.description}
                        </span>
                      )}
                    </label>
                    <DeltaGuardInput
                      varKey={key}
                      value={row.value ?? 0}
                      onChange={(val) => updateDraftLogicVar(key, val)}
                      step={stepFor(key, row.value ?? 0)}
                    />
                  </div>
                );
              })}
            </div>
          </section>
        );
      })}
    </div>
  );
}
