// SPEC LINK: docs/specs/01-pipeline/68_mcbylaw_standard.md §9 G-TEXT (ids and clause paths unique;
//            slices round-trip; per-page counts equal the lock; slices + declared non-regulation spans
//            cover each page; numbering sequence incl. the case-insensitive definition matcher;
//            verbatim equals the slice; clauses concatenate to the verbatim; source defects are
//            counted disclosures, never failures), §8 rule 8 (module shape), §6.4 rules 1, 9, 11;
//            docs/specs/01-pipeline/69_mcbylaw_policy.md M-2, M-47; docs/reports/mcbylaw-phase1-plan.md S4.
//
// STANDARDIZED word module. S4 lands G-TEXT; G-SHAPE (S6) is added here by its step. The unit-pin
// arm of G-TEXT (`pending:stale`) needs authored units and lands with them (S6); this module
// generates the per-unit shas that arm compares against (slice.lock.json).
//
// Reason codes (closed set, G-TEXT):
//   duplicate_id                 two rows (or two units) share an id
//   slice_mismatch               a row's verbatim is not the page slice at its offsets, or its sha differs
//   clauses_not_concatenating    a row's clauses do not partition and concatenate to its verbatim
//   page_not_covered             non-whitespace page text outside every row and declared span
//   span_overlap                 two rows / spans overlap on a page
//   unsliced_head                a numbered regulation or (n) Term head that fits the sequence is not a row
//   heading_not_found            a TOC heading of the page is not found in its body
//   body_not_found               the page has no section heading after its TOC
//   toc_missing_section          the page TOC lacks its chapter or section row
//   carve_in_not_found           a declared carve-in article is not on its page
//   empty_article                an article heading with no text
//   text_before_first_regulation article text before its (1) that no row holds
//   lock_missing                 no slice.lock.json
//   lock_stale                   the lock was generated for another adoption, normalizer or slicer version
//   count_mismatch               a per-page count differs from the lock (either direction)
// Disclosures (counted, never failures): source_defect (garbled_character, lead_in_without_items,
// heading_not_in_toc, division_repeat, numbering_repeat, marker_typo) and numbering gaps.

import fs from 'node:fs';
import path from 'node:path';
import { sha256, stableStringify, writeAtomic } from './snapshot.mjs';
import { DEFINITION_MATCHER, PHASE0_DEFINITION_MATCHER, SLICER_VERSION, loadSnapshotPages, sliceSnapshot } from './slice.mjs';

export const LOCK_FILE = 'slice.lock.json';
/** Per-page counts the lock pins (Spec 68 §9 G-TEXT "per-page counts equal the lock"). */
export const LOCKED_COUNTS = Object.freeze(['definitions', 'retired_rows', 'rows', 'units']);

const isWs = (s) => /^\s*$/.test(s);

/** The generated lock: per-page counts + every row and unit sha, bound to the adoption. PURE. */
export function buildSliceLock(slice, { adoption_id, normalizer_version }) {
  const pages = {};
  for (const [k, c] of Object.entries(slice.pages)) pages[k] = Object.fromEntries(LOCKED_COUNTS.map((f) => [f, c[f]]));
  const totals = Object.fromEntries(LOCKED_COUNTS.map((f) => [f, Object.values(pages).reduce((s, c) => s + c[f], 0)]));
  return {
    $comment: 'GENERATED by scripts/analysis/bylaw/standardized.mjs writeSliceLock() from the adopted pages (Spec 68 §9 G-TEXT). Do not edit. A change re-pins only under a new adoption.',
    adoption_id,
    normalizer_version,
    pages,
    rows: Object.fromEntries(slice.rows.map((r) => [r.regulation_id, r.sha256])),
    slicer_version: slice.slicer_version,
    totals,
    units: Object.fromEntries(slice.units.map((u) => [u.unit_id, u.sha256])),
  };
}

/**
 * G-TEXT over an in-memory slice. `pages` = {key: normalized text}; `lock` may be null; `expect` =
 * {adoption_id, normalizer_version} the lock must be bound to. Returns {pass, violations, checked,
 * disclosures}. PURE.
 */
export function checkTextSlice({ slice, pages, lock, expect }) {
  const violations = [];
  let checked = 0;
  const seenRows = new Set();
  for (const r of slice.rows) {
    checked++;
    if (seenRows.has(r.regulation_id)) violations.push(`duplicate_id: row ${r.regulation_id}`);
    seenRows.add(r.regulation_id);
    const text = pages[r.page];
    if (text === undefined || text.slice(r.start, r.end) !== r.verbatim || sha256(Buffer.from(r.verbatim, 'utf8')) !== r.sha256) {
      violations.push(`slice_mismatch: ${r.regulation_id} verbatim is not ${r.page}[${r.start}, ${r.end})`);
    }
    let pos = 0;
    let ok = true;
    for (const c of r.clauses) {
      if (c.start !== pos || r.verbatim.slice(c.start, c.end) !== c.text) ok = false;
      pos = c.end;
    }
    if (!ok || pos !== r.verbatim.length || r.clauses.map((c) => c.text).join('') !== r.verbatim) {
      violations.push(`clauses_not_concatenating: ${r.regulation_id}`);
    }
  }
  const seenUnits = new Set();
  for (const u of slice.units) {
    if (seenUnits.has(u.unit_id)) violations.push(`duplicate_id: unit ${u.unit_id}`);
    seenUnits.add(u.unit_id);
  }
  // Coverage: rows + declared spans cover each sliced page; nothing overlaps.
  for (const [key, spans] of Object.entries(slice.spans)) {
    const text = pages[key] ?? '';
    const iv = [...spans.map((s) => ({ start: s.start, end: s.end, what: s.kind })), ...slice.rows.filter((r) => r.page === key).map((r) => ({ start: r.start, end: r.end, what: r.regulation_id }))].sort((a, b) => a.start - b.start || a.end - b.end);
    let pos = 0;
    let prev = null;
    for (const x of iv) {
      if (x.start < pos) violations.push(`span_overlap: ${key} ${prev.what} [${prev.start}, ${prev.end}) and ${x.what} [${x.start}, ${x.end})`);
      else if (!isWs(text.slice(pos, x.start))) violations.push(`page_not_covered: ${key} [${pos}, ${x.start}) "${text.slice(pos, Math.min(x.start, pos + 60))}"`);
      if (x.end > pos) {
        pos = x.end;
        prev = x;
      }
    }
    if (!isWs(text.slice(pos))) violations.push(`page_not_covered: ${key} [${pos}, ${text.length}) "${text.slice(pos, pos + 60)}"`);
  }
  for (const u of slice.numbering.unsliced) violations.push(`unsliced_head: ${u.key} ${u.article} (${u.n}) "${u.context}"`);
  for (const p of slice.problems) violations.push(p);
  // The lock.
  if (!lock) violations.push(`lock_missing: ${LOCK_FILE}`);
  else {
    if (lock.adoption_id !== expect.adoption_id || lock.normalizer_version !== expect.normalizer_version || lock.slicer_version !== slice.slicer_version) {
      violations.push(`lock_stale: lock ${lock.adoption_id}/${lock.normalizer_version}/${lock.slicer_version} != ${expect.adoption_id}/${expect.normalizer_version}/${slice.slicer_version}`);
    }
    const keys = new Set([...Object.keys(lock.pages || {}), ...Object.keys(slice.pages)]);
    for (const k of [...keys].sort()) {
      for (const f of LOCKED_COUNTS) {
        const want = lock.pages?.[k]?.[f];
        const got = slice.pages[k]?.[f];
        if (want !== got) violations.push(`count_mismatch: ${k}.${f} lock ${want ?? 'absent'} != slice ${got ?? 'absent'}`);
      }
    }
  }
  const disclosures = { numbering_gaps: slice.numbering.gaps.length, source_defect: slice.defects.length, source_defect_by_kind: {} };
  for (const d of slice.defects) disclosures.source_defect_by_kind[d.kind] = (disclosures.source_defect_by_kind[d.kind] || 0) + 1;
  return { checked, disclosures, pass: violations.length === 0, violations };
}

function readLock(seeds) {
  const f = path.join(seeds, LOCK_FILE);
  return fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf8')) : null;
}

/** Slice the committed snapshot. Returns {snap, slice, pages{key: text}}. */
export function sliceSeeds(seeds) {
  const snap = loadSnapshotPages(seeds);
  const slice = sliceSnapshot({ pages: snap.pages });
  return { pages: Object.fromEntries(snap.pages.map((p) => [p.key, p.normalized])), slice, snap };
}

/** G-TEXT over the committed snapshot and lock. Returns {pass, violations, checked, disclosures}. */
export function checkText({ seeds }) {
  const { pages, slice, snap } = sliceSeeds(seeds);
  return checkTextSlice({ expect: { adoption_id: snap.adoption_id, normalizer_version: snap.normalizer_version }, lock: readLock(seeds), pages, slice });
}

/** Generate the lock from the adopted pages (the adopt step's job; proposed CLI wiring in the S4 report). */
export function writeSliceLock({ seeds }) {
  const { slice, snap } = sliceSeeds(seeds);
  const lock = buildSliceLock(slice, { adoption_id: snap.adoption_id, normalizer_version: snap.normalizer_version });
  writeAtomic(path.join(seeds, LOCK_FILE), stableStringify(lock));
  return lock;
}

// ---------------------------------------------------------------- fixtures (known-bad + good twin)

const FILE = (section) => `ZBL_NewProvision_Chapter${section.replace('.', '_')}.htm`;

/**
 * A City-shaped page: header, TOC table (chapter, section, own `#` article rows), body, footer.
 * `articles` = [{id, title, text}] (text after the heading; `heading: false` omits it from the body);
 * `sectionText` = body text directly under the section heading (a page with no articles, e.g. 800.50).
 * Returns a sliceSnapshot() page input. PURE.
 */
export function fixturePage({ key = 'ch10_20', chapter = '10', chapterTitle = 'Residential', section = '10.20', sectionTitle = 'Residential Detached Zone (RD)', articles = [], sectionText = '', status, ruling, carve_in }) {
  const toc = [
    `<TR><TD>Chapter ${chapter}</TD><TD><A HREF="ZBL_NewProvision_Chapter${chapter}.htm">${chapterTitle}</A></TD></TR>`,
    `<TR><TD>${section}</TD><TD><A HREF="${FILE(section)}">${sectionTitle}</A></TD></TR>`,
    ...articles.map((a) => `<TR><TD>${a.id}</TD><TD><A HREF="#${a.id}">${a.title}</A></TD></TR>`),
  ];
  const body = [sectionText, ...articles.filter((a) => a.heading !== false).map((a) => `${a.id} ${a.title} ${a.text}`)].filter(Boolean).join(' ');
  const html = [
    '<html><head><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body>',
    '<p>City of Toronto Zoning By-law 569-2013 Version Date: July 31, 2024, including City-wide Amendments up to April 30, 2026 Table of Contents</p>',
    `<TABLE>${toc.join('')}</TABLE>`,
    `<p>Chapter ${chapter} ${chapterTitle} ${section} ${sectionTitle} ${body}</p>`,
    '<p>&copy;City of Toronto 1998-2026</p></body></html>',
  ].join('\n');
  const normalized = html
    .replace(/<[^>]+>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  return { carve_in, file: FILE(section), html, key, normalized, role: 'section', ruling, section, status };
}

const GOOD_ARTICLES = [
  { id: '10.20.40.10', title: 'Height', text: '(1) Maximum Height The permitted maximum height of a building is 10.0 metres. [ By-law: 1-2020 ] (2) Storeys The permitted maximum number of storeys is 2.' },
  { id: '10.20.40.70', title: 'Setbacks', text: '(1) Side Yard The required minimum side yard setback is: (A) 0.9 metres, if the lot frontage is less than 12.0 metres; and (B) 1.2 metres, in all other cases. [ By-law: 2-2021 ]' },
];
function defsFixture(matcher) {
  const sectionText = '(405) Landscaping means trees and plants. (410) Lawfully Existing Means: in compliance with a by-law. (415) Lot means a parcel of land.';
  return { pages: [fixturePage({ key: 'ch800_50', chapter: '800', chapterTitle: 'Definitions', section: '800.50', sectionTitle: 'Defined Terms', sectionText })], matcher };
}

function run({ pages, matcher, mutate, lockFrom, lockMutate }) {
  const slice = sliceSnapshot({ pages, definitionMatcher: matcher });
  const expect = { adoption_id: 'adoption-1', normalizer_version: 'norm-v1' };
  let lock = buildSliceLock(lockFrom ? sliceSnapshot({ pages: lockFrom }) : slice, expect);
  if (mutate) mutate(slice);
  if (lockMutate) lock = lockMutate(lock);
  return checkTextSlice({ expect, lock, pages: Object.fromEntries(pages.map((p) => [p.key, p.normalized])), slice });
}

const good = () => [fixturePage({ articles: GOOD_ARTICLES })];

/** One known-bad fixture per reason code, each with the good twin it differs from. */
export const FIXTURES = Object.freeze([
  { reason: null, name: 'good twin: clean page', input: () => ({ pages: good() }) },
  { reason: null, name: 'good twin: case-insensitive matcher slices (410) Lawfully Existing Means', input: () => defsFixture(DEFINITION_MATCHER) },
  { reason: 'duplicate_id', name: 'a row duplicated', input: () => ({ pages: good(), mutate: (s) => s.rows.push({ ...s.rows[0], start: s.rows[0].start }) }) },
  { reason: 'slice_mismatch', name: 'verbatim edited', input: () => ({ pages: good(), mutate: (s) => (s.rows[0].verbatim = s.rows[0].verbatim.replace('10.0', '11.0')) }) },
  { reason: 'clauses_not_concatenating', name: 'a clause dropped', input: () => ({ pages: good(), mutate: (s) => s.rows.find((r) => r.clauses.length > 1).clauses.pop() }) },
  { reason: 'page_not_covered', name: 'a row missing from the slice', input: () => ({ pages: good(), mutate: (s) => s.rows.splice(1, 1) }) },
  { reason: 'span_overlap', name: 'a declared span overlaps a row', input: () => ({ pages: good(), mutate: (s) => s.spans.ch10_20.push({ start: s.rows[0].start, end: s.rows[0].start + 5, kind: 'article_heading' }) }) },
  { reason: 'unsliced_head', name: 'the Phase 0 matcher misses (410) Lawfully Existing Means', input: () => defsFixture(PHASE0_DEFINITION_MATCHER) },
  { reason: 'unsliced_head', name: 'a regulation head the slicer skipped', input: () => ({ pages: good(), mutate: (s) => s.numbering.unsliced.push({ key: 'ch10_20', article: '10.20.40.10', n: 2, context: 'x' }) }) },
  { reason: 'heading_not_found', name: 'a TOC article absent from the body', input: () => ({ pages: [fixturePage({ articles: [...GOOD_ARTICLES, { id: '10.20.40.80', title: 'Separation', text: '', heading: false }] })] }) },
  { reason: 'carve_in_not_found', name: 'a carve-in article that is not on the page', input: () => ({ pages: [fixturePage({ articles: GOOD_ARTICLES, carve_in: ['10.20.40.99'] })] }) },
  { reason: 'empty_article', name: 'an article heading with no text', input: () => ({ pages: [fixturePage({ articles: [...GOOD_ARTICLES, { id: '10.20.40.80', title: 'Separation', text: '' }] })] }) },
  { reason: 'text_before_first_regulation', name: 'article text before (1)', input: () => ({ pages: [fixturePage({ articles: [{ id: '10.20.40.10', title: 'Height', text: 'Preamble text. (1) Maximum Height The height is 10.0 metres.' }] })] }) },
  { reason: 'lock_missing', name: 'no lock', input: () => ({ pages: good(), lockMutate: () => null }) },
  { reason: 'lock_stale', name: 'lock bound to another adoption', input: () => ({ pages: good(), lockMutate: (l) => ({ ...l, adoption_id: 'adoption-0' }) }) },
  { reason: 'count_mismatch', name: 'lock pins a different row count', input: () => ({ pages: good(), lockFrom: [fixturePage({ articles: GOOD_ARTICLES.slice(0, 1) })] }) },
]);

/** Run every fixture: a known-bad one must fail with its reason; a good twin must pass. */
export function selfTest() {
  const results = FIXTURES.map((f) => {
    const r = run(f.input());
    const ok = f.reason === null ? r.pass : !r.pass && r.violations.some((v) => v.startsWith(`${f.reason}:`));
    return { name: f.name, ok, reason: f.reason, violations: r.violations };
  });
  return { pass: results.every((x) => x.ok), results };
}
