// SPEC LINK: docs/specs/01-pipeline/68_mcbylaw_standard.md §9 G-TEXT (ids and clause paths unique; slices
//            round-trip; per-page counts equal the lock; slices + declared non-regulation spans cover each page;
//            the unit set equals the HTML clause-cell set + declared inline splits, both directions; a numbering
//            gap at any level fails unless the page proves the number absent; repeats are status-tagged variants,
//            an unstatused variant with different numbers fails; source defects are counted disclosures), §8 rule 8
//            (module shape); docs/specs/01-pipeline/69_mcbylaw_policy.md M-2, M-36, M-57 (operator rulings R1–R5,
//            2026-10-07); docs/reports/mcbylaw-phase1-plan.md S4 (rework).
//
// STANDARDIZED word module: G-TEXT (S4). G-SHAPE (S6) is added here by its step. The unit-pin arm
// (`pending:stale`) compares authored pins against the unit shas this module locks.
//
// Reason codes (closed set, G-TEXT):
//   duplicate_id                 two rows (or two units) share an id
//   slice_mismatch               a row's verbatim is not its page (or enacting text) slice, or its sha differs
//   clauses_not_concatenating    a row's clause ranges do not partition its verbatim, or a clause text differs
//   page_not_covered             non-whitespace page text outside every row and declared span
//   span_overlap                 two rows / spans overlap on a page
//   numbering_gap_unproven       a gap (or a swallowed division) at any level the page does not prove absent (R3)
//   unstatused_variant           a repeated division with no status whose numbers differ from the first (R4)
//   cell_set_mismatch            the page's clause cells != the sliced cell nodes (R1, both directions)
//   inline_split_undeclared      an inline-list unit not in the lock's declared splits, or a declared one gone (R1)
//   normalizer_map_mismatch      the raw→normalized map does not reproduce the pinned normalized page
//   row_not_contiguous           a row's characters interleave with another row's
//   footer_not_found             the page footer that ends the content is missing
//   lock_missing                 no slice.lock.json
//   lock_stale                   the lock was generated for another adoption, normalizer or slicer version
//   count_mismatch               a per-page count differs from the lock (either direction)
// Disclosures (counted, never failures): source_defect (garbled_character, lead_in_without_items,
// heading_not_in_toc, anchor_mismatch, variant_duplicate, division_repeat, marker_typo) and proven numbering gaps.

import fs from 'node:fs';
import path from 'node:path';
import { normalize, sha256, stableStringify, writeAtomic } from './snapshot.mjs';
import { loadSnapshotPages, sliceSnapshot } from './slice.mjs';

export const LOCK_FILE = 'slice.lock.json';
/** Per-page counts the lock pins (Spec 68 §9 G-TEXT "per-page counts equal the lock"). */
export const LOCKED_COUNTS = Object.freeze(['cells_sliced', 'definitions', 'inline_units', 'retired_rows', 'rows', 'table_units', 'units']);
/** Problem prefixes of the slicer that are G-TEXT reason codes. */
const SLICER_CODES = Object.freeze(['cell_set_mismatch', 'footer_not_found', 'normalizer_map_mismatch', 'row_not_contiguous', 'unstatused_variant']);

const isWs = (s) => /^\s*$/.test(s);

/** The generated lock: per-page counts, the declared inline splits, every row and unit sha, bound to the adoption. PURE. */
export function buildSliceLock(slice, { adoption_id, normalizer_version }) {
  const pages = {};
  for (const [k, c] of Object.entries(slice.pages)) pages[k] = Object.fromEntries(LOCKED_COUNTS.map((f) => [f, c[f]]));
  const totals = Object.fromEntries(LOCKED_COUNTS.map((f) => [f, Object.values(pages).reduce((s, c) => s + c[f], 0)]));
  return {
    $comment: 'GENERATED by scripts/analysis/bylaw/standardized.mjs writeSliceLock() from the adopted pages and the sliced enacting texts (Spec 68 §9 G-TEXT). Do not edit. A change re-pins only under a new adoption.',
    adoption_id,
    inline_splits: slice.units.filter((u) => u.origin === 'inline').map((u) => u.unit_id).sort(),
    normalizer_version,
    pages,
    rows: Object.fromEntries(slice.rows.map((r) => [r.regulation_id, r.sha256])),
    slicer_version: slice.slicer_version,
    totals,
    units: Object.fromEntries(slice.units.map((u) => [u.unit_id, u.sha256])),
  };
}

/**
 * G-TEXT over an in-memory slice. `pages` = {key: text} (section pages and `enacting:<bylaw>` texts); `lock`
 * may be null; `expect` = {adoption_id, normalizer_version}. Returns {pass, violations, checked, disclosures}. PURE.
 */
export function checkTextSlice({ slice, pages, lock, expect }) {
  const violations = [];
  let checked = 0;
  const seenRows = new Set();
  for (const r of slice.rows) {
    checked++;
    if (seenRows.has(r.regulation_id)) violations.push(`duplicate_id: row ${r.regulation_id}`);
    seenRows.add(r.regulation_id);
    const text = pages[r.page];
    if (text === undefined || text.slice(r.start, r.end) !== r.verbatim || sha256(Buffer.from(r.verbatim, 'utf8')) !== r.sha256) {
      violations.push(`slice_mismatch: ${r.regulation_id} verbatim is not ${r.page}[${r.start}, ${r.end})`);
    }
    const ranges = r.clauses.flatMap((c) => c.ranges).sort((a, b) => a[0] - b[0]);
    let pos = 0;
    let ok = r.clauses.every((c) => c.ranges.map(([s, e]) => r.verbatim.slice(s, e)).join('') === c.text);
    for (const [s, e] of ranges) {
      if (s !== pos || e <= s) ok = false;
      pos = e;
    }
    if (!ok || pos !== r.verbatim.length) violations.push(`clauses_not_concatenating: ${r.regulation_id}`);
  }
  const seenUnits = new Set();
  for (const u of slice.units) {
    if (seenUnits.has(u.unit_id)) violations.push(`duplicate_id: unit ${u.unit_id}`);
    seenUnits.add(u.unit_id);
  }
  for (const [key, spans] of Object.entries(slice.spans)) {
    const text = pages[key] ?? '';
    const iv = [...spans.map((s) => ({ end: s.end, start: s.start, what: s.kind })), ...slice.rows.filter((r) => r.page === key).map((r) => ({ end: r.end, start: r.start, what: r.regulation_id }))].sort((a, b) => a.start - b.start || a.end - b.end);
    let pos = 0;
    let prev = null;
    for (const x of iv) {
      if (x.start < pos) violations.push(`span_overlap: ${key} ${prev.what} [${prev.start}, ${prev.end}) and ${x.what} [${x.start}, ${x.end})`);
      else if (!isWs(text.slice(pos, x.start))) violations.push(`page_not_covered: ${key} [${pos}, ${x.start}) "${text.slice(pos, Math.min(x.start, pos + 60))}"`);
      if (x.end > pos) {
        pos = x.end;
        prev = x;
      }
    }
    if (!isWs(text.slice(pos))) violations.push(`page_not_covered: ${key} [${pos}, ${text.length}) "${text.slice(pos, pos + 60)}"`);
  }
  for (const g of slice.numbering.unproven) violations.push(`numbering_gap_unproven: ${g.key} ${g.article} ${g.parent || '(article)'} (${g.missing}) after (${g.after ?? '-'}) before (${g.next ?? '-'})${g.context ? ` "${g.context}"` : ''}`);
  for (const p of slice.problems) violations.push(SLICER_CODES.some((c) => p.startsWith(`${c}:`)) ? p : `structural: ${p}`);
  if (!lock) violations.push(`lock_missing: ${LOCK_FILE}`);
  else {
    if (lock.adoption_id !== expect.adoption_id || lock.normalizer_version !== expect.normalizer_version || lock.slicer_version !== slice.slicer_version) {
      violations.push(`lock_stale: lock ${lock.adoption_id}/${lock.normalizer_version}/${lock.slicer_version} != ${expect.adoption_id}/${expect.normalizer_version}/${slice.slicer_version}`);
    }
    const keys = new Set([...Object.keys(lock.pages || {}), ...Object.keys(slice.pages)]);
    for (const k of [...keys].sort()) {
      for (const f of LOCKED_COUNTS) {
        const want = lock.pages?.[k]?.[f];
        const got = slice.pages[k]?.[f];
        if (want !== got) violations.push(`count_mismatch: ${k}.${f} lock ${want ?? 'absent'} != slice ${got ?? 'absent'}`);
      }
    }
    const declared = new Set(lock.inline_splits || []);
    const now = new Set(slice.units.filter((u) => u.origin === 'inline').map((u) => u.unit_id));
    for (const id of now) if (!declared.has(id)) violations.push(`inline_split_undeclared: ${id} is an inline split the lock does not declare`);
    for (const id of declared) if (!now.has(id)) violations.push(`inline_split_undeclared: declared ${id} is no longer split`);
  }
  const disclosures = { numbering_gaps: slice.numbering.gaps.length, source_defect: slice.defects.length, source_defect_by_kind: {} };
  for (const d of slice.defects) disclosures.source_defect_by_kind[d.kind] = (disclosures.source_defect_by_kind[d.kind] || 0) + 1;
  return { checked, disclosures, pass: violations.length === 0, violations };
}

function readLock(seeds) {
  const f = path.join(seeds, LOCK_FILE);
  return fs.existsSync(f) ? JSON.parse(fs.readFileSync(f, 'utf8')) : null;
}

/** Slice the committed snapshot (pages + sliced enacting texts). Returns {snap, slice, pages{key: text}}. */
export function sliceSeeds(seeds) {
  const snap = loadSnapshotPages(seeds);
  const slice = sliceSnapshot(snap);
  const pages = Object.fromEntries(snap.pages.map((p) => [p.key, p.normalized]));
  for (const e of snap.enacting) pages[`enacting:${e.bylaw}`] = e.text;
  return { pages, slice, snap };
}

/** G-TEXT over the committed snapshot and lock. Returns {pass, violations, checked, disclosures}. */
export function checkText({ seeds }) {
  const { pages, slice, snap } = sliceSeeds(seeds);
  return checkTextSlice({ expect: { adoption_id: snap.adoption_id, normalizer_version: snap.normalizer_version }, lock: readLock(seeds), pages, slice });
}

/** Generate the lock from the adopted pages (the adopt step's job; proposed CLI wiring in the S4 report). */
export function writeSliceLock({ seeds }) {
  const { slice, snap } = sliceSeeds(seeds);
  const lock = buildSliceLock(slice, { adoption_id: snap.adoption_id, normalizer_version: snap.normalizer_version });
  writeAtomic(path.join(seeds, LOCK_FILE), stableStringify(lock));
  return lock;
}

// ---------------------------------------------------------------- fixtures (known-bad + good twin)

const FILE = (section) => `ZBL_NewProvision_Chapter${section.replace('.', '_')}.htm`;
const MARK = (sym, anchor) => `<TD ALIGN=RIGHT VALIGN=TOP width="5%">${anchor ? `<A Name="${anchor}">(${sym})</A>` : `(${sym})`}</TD>`;
const CONT = '<TD ALIGN=RIGHT VALIGN=TOP width="5%"></TD>';

/** A clause table: [{sym, text, clauses?, html?}] → nested City markup (depth = table nesting). */
export function clauseTable(items) {
  return `<TABLE WIDTH="100%">${items
    .map((c) => `<TR>${MARK(c.sym)}<TD VALIGN=TOP colspan="2">${c.text}</TD></TR>${c.clauses ? `<TR>${CONT}<TD VALIGN=TOP>${clauseTable(c.clauses)}</TD></TR>` : ''}${c.html || ''}`)
    .join('')}</TABLE>`;
}

/** A regulation: {n, title, text?, clauses?, html?} under `article`. */
export function regulationHtml(article, reg) {
  return `<TABLE WIDTH="100%"><TR>${MARK(reg.n, reg.anchor === false ? null : `${article}(${reg.n})`)}<TD VALIGN=TOP colspan="2"><u>${reg.title}</u></TD></TR>${reg.text ? `<TR>${CONT}<TD VALIGN=TOP colspan="2">${reg.text}<br></TD></TR>` : ''}${reg.clauses ? `<TR>${CONT}<TD VALIGN=TOP>${clauseTable(reg.clauses)}</TD></TR>` : ''}${reg.html || ''}</TABLE>`;
}

/**
 * A City-shaped page: header, TOC table, the content cell (H1 chapter, H2 section, H4 articles with their
 * regulation tables) and the footer. `articles` = [{id, title, regs: [...], toc?: false}]. Returns a
 * sliceSnapshot() page input whose `normalized` is normalize(html) (the pinned-page contract). PURE.
 */
export function fixturePage({ key = 'ch10_20', chapter = '10', chapterTitle = 'Residential', section = '10.20', sectionTitle = 'Residential Detached Zone (RD)', articles = [], status, ruling, carve_in }) {
  const toc = [
    `<TR><TD>Chapter ${chapter}</TD><TD><A HREF="ZBL_NewProvision_Chapter${chapter}.htm">${chapterTitle}</A></TD></TR>`,
    `<TR><TD>${section}</TD><TD><A HREF="${FILE(section)}">${sectionTitle}</A></TD></TR>`,
    ...articles.filter((a) => a.toc !== false).map((a) => `<TR><TD>${a.id}</TD><TD><A HREF="#${a.id}">${a.title}</A></TD></TR>`),
  ];
  const body = articles.map((a) => `<H4><A Name="${a.id}">${a.id}   ${a.title}</A></H4>${(a.regs || []).map((r) => regulationHtml(a.id, r)).join('')}`).join('\n');
  const html = [
    '<html><head><META http-equiv="Content-Type" content="text/html; charset=iso-8859-1"></head><body>',
    '<p>City of Toronto Zoning By-law 569-2013 Version Date: July 31, 2024, including City-wide Amendments up to April 30, 2026 Table of Contents</p>',
    `<TABLE>${toc.join('')}</TABLE>`,
    `<TABLE><TR><TD VALIGN="TOP"><H1>Chapter ${chapter}      ${chapterTitle}</H1><H2>${section}  ${sectionTitle}</H2>${body}</TD></TR></TABLE>`,
    '<table><tr><td align="right"><font>&copy;<A href="http://www.toronto.ca/copyright.htm">City of Toronto 1998-2026</A></font></td></tr></table></body></html>',
  ].join('\n');
  return { carve_in, file: FILE(section), html, key, normalized: normalize(html), role: 'section', ruling, section, status };
}

const GOOD = () => [
  fixturePage({
    articles: [
      { id: '10.20.40.10', regs: [{ n: 1, text: 'The permitted maximum height of a building is 10.0 metres. [ By-law: 1-2020 ]', title: 'Maximum Height' }, { n: 2, text: 'The permitted maximum number of storeys is 2.', title: 'Storeys' }], title: 'Height' },
      { id: '10.20.40.70', regs: [{ clauses: [{ sym: 'A', text: '0.9 metres, if the lot frontage is less than 12.0 metres; and' }, { sym: 'B', text: '1.2 metres, in all other cases. [ By-law: 2-2021 ]' }], n: 1, text: 'The required minimum side yard setback is:', title: 'Side Yard' }], title: 'Setbacks' },
    ],
  }),
];
const EXPECT = { adoption_id: 'adoption-1', normalizer_version: 'norm-v1' };

function run({ pages, mutate, lockFrom, lockMutate }) {
  const slice = sliceSnapshot({ pages });
  let lock = buildSliceLock(lockFrom ? sliceSnapshot({ pages: lockFrom }) : slice, EXPECT);
  if (mutate) mutate(slice);
  if (lockMutate) lock = lockMutate(lock);
  return checkTextSlice({ expect: EXPECT, lock, pages: Object.fromEntries(pages.map((p) => [p.key, p.normalized])), slice });
}

const one = (regs, extra = {}) => [fixturePage({ articles: [{ id: '10.20.40.70', regs, title: 'Setbacks' }], ...extra })];

/** One known-bad fixture per reason code, each with the good twin it differs from. */
export const FIXTURES = Object.freeze([
  { input: () => ({ pages: GOOD() }), name: 'good twin: clean page', reason: null },
  { input: () => ({ pages: one([{ clauses: [{ sym: 'A', text: 'a;' }, { sym: 'B', text: 'b.' }], n: 1, text: 'Lead:', title: 'T' }, { n: 2, text: 'x', title: 'U' }, { n: 4, text: 'y', title: 'V' }]) }), name: 'good twin: a gap the page proves absent ((3) appears nowhere) is a counted disclosure', reason: null },
  { input: () => ({ pages: one([{ n: 1, text: 'x', title: 'T' }, { html: '', n: 1, text: 'x [ By-law: 9-2020 Under Appeal ]', title: 'T' }]) }), name: 'good twin: an Under Appeal variant is a status-tagged row', reason: null },
  { input: () => ({ mutate: (s) => s.rows.push({ ...s.rows[0] }), pages: GOOD() }), name: 'a row duplicated', reason: 'duplicate_id' },
  { input: () => ({ mutate: (s) => (s.rows[0].verbatim = s.rows[0].verbatim.replace('10.0', '11.0')), pages: GOOD() }), name: 'verbatim edited', reason: 'slice_mismatch' },
  { input: () => ({ mutate: (s) => s.rows.find((r) => r.clauses.length > 1).clauses.pop(), pages: GOOD() }), name: 'a clause dropped', reason: 'clauses_not_concatenating' },
  { input: () => ({ mutate: (s) => s.rows.splice(1, 1), pages: GOOD() }), name: 'a row missing from the slice', reason: 'page_not_covered' },
  { input: () => ({ mutate: (s) => s.spans.ch10_20.push({ end: s.rows[0].start + 5, kind: 'heading', start: s.rows[0].start }), pages: GOOD() }), name: 'a declared span overlaps a row', reason: 'span_overlap' },
  { input: () => ({ pages: one([{ n: 1, text: 'x. (2) Swallowed Rear yard is 7.5 metres. y', title: 'T' }, { n: 3, text: 'z', title: 'V' }]) }), name: 'a regulation whose cell the page lost: (2) is in the text, not a cell', reason: 'numbering_gap_unproven' },
  { input: () => ({ pages: one([{ clauses: [{ sym: 'A', text: 'length of 6.0 metres (B) width of 3.2 metres' }], n: 3, text: 'Minimum:', title: 'T' }]) }), name: 'class A: (B) swallowed inside the (A) cell', reason: 'numbering_gap_unproven' },
  { input: () => ({ pages: one([{ clauses: [{ sym: 'A', text: 'x;' }, { sym: 'B', text: 'width of 3.9 metres' }, { sym: 'B', text: 'width of 3.4 metres' }], n: 1, text: 'Dims:', title: 'T' }]) }), name: 'an unstatused repeat with different numbers (200.15.1(1)(B))', reason: 'unstatused_variant' },
  { input: () => ({ mutate: (s) => s.problems.push('cell_set_mismatch: ch10_20 html clause cells 5 != sliced 4'), pages: GOOD() }), name: 'the cell set and the slice disagree', reason: 'cell_set_mismatch' },
  { input: () => ({ lockMutate: (l) => ({ ...l, inline_splits: [] }), pages: one([{ n: 1, text: 'Rates: (A) in Zone A 1.0; and (B) in Zone B 2.0.', title: 'T' }]) }), name: 'an inline split the lock does not declare', reason: 'inline_split_undeclared' },
  { input: () => ({ lockMutate: () => null, pages: GOOD() }), name: 'no lock', reason: 'lock_missing' },
  { input: () => ({ lockMutate: (l) => ({ ...l, adoption_id: 'adoption-0' }), pages: GOOD() }), name: 'lock bound to another adoption', reason: 'lock_stale' },
  { input: () => ({ lockFrom: one([{ n: 1, text: 'x', title: 'T' }]), pages: GOOD() }), name: 'lock pins different counts', reason: 'count_mismatch' },
]);

/** Run every fixture: a known-bad one must fail with its reason; a good twin must pass. */
export function selfTest() {
  const results = FIXTURES.map((f) => {
    const r = run(f.input());
    const ok = f.reason === null ? r.pass : !r.pass && r.violations.some((v) => v.startsWith(`${f.reason}:`));
    return { name: f.name, ok, reason: f.reason, violations: r.violations };
  });
  return { pass: results.every((x) => x.ok), results };
}
