// SPEC LINK: docs/specs/01-pipeline/122_pipeline_step_optimization.md §1.4, §6.6.1; O4 row 5 (registry-truth folds 14 + 15) — link_massing full_rescan, rewrite only changed links
//
// O4 row 5 (operator ruling 2026-10-03, folds 14/15): link_massing re-derives EVERY eligible parcel's links
// every run (staleness.mode_select "none" — full_rescan), but REWRITES ONLY CHANGED links:
//   · NO mass retraction (the old FULL-mode `DELETE … retract all` deleted and re-inserted every link, which
//     moved every linked_at and cascaded a full enrich_parcels re-enrich);
//   · the primary clear is GUARDED against the derived primary, so an unchanged primary is never cleared
//     (and therefore never re-set by the guarded upsert — linked_at does not move);
//   · links no longer derived get a KEYED per-batch delete in the batch transaction (link_keyed precedent);
//   · a parcel that LOST a link is flagged (parcels.massing_enriched_at := NULL) in the same transaction, so
//     enrich_parcels recomputes just that parcel.
// Fixture: parcel 1 keeps (1,10) [unchanged], parcel 2 loses (2,20) [building moved away], parcel 3 gains (3,30).

import { afterEach, describe, expect, it, vi } from 'vitest';
import { join } from 'node:path';

/* eslint-disable @typescript-eslint/no-require-imports */
const stepLib = require(join(process.cwd(), 'scripts/lib/step'));
const writeLib = require(join(process.cwd(), 'scripts/lib/step/write.js'));
const compute = require(join(process.cwd(), 'scripts/lib/compute/link-massing.js'));
const REAL = require(join(process.cwd(), 'scripts/link-massing.descriptor.json'));
/* eslint-enable @typescript-eslint/no-require-imports */

const clone = <T>(o: T): T => JSON.parse(JSON.stringify(o));
const NOOP_LOG = { info: () => {}, warn: () => {}, error: () => {} };
const RUN_AT = new Date('2026-10-03T12:00:00Z');
const CONFIG = Object.freeze({
  massing_shed_threshold_sqm: 15,
  massing_garage_max_sqm: 60,
  massing_nearest_max_distance_m: 50,
  link_massing_centroid_confidence: 0.95,
  link_massing_nearest_confidence: 0.6,
});

/** The FLEET-2 target descriptor shape for row 5 (seat B lands the real edit; this fixture pins it). */
function row5Descriptor() {
  const d = clone(REAL);
  d.guards.requires = [];
  d.staleness.trigger = 'none';
  d.staleness.mode_select = 'none';
  // E1 stays GENERATED by write.js; the derived-primary guard lives in its declared scope.
  d.outputs.writes[0].write_discipline.scope = compute.PRIMARY_CLEAR_SCOPE;
  d.outputs.writes[1].retract = 'none';
  delete d.outputs.writes[1].retract_when;
  d.outputs.writes.push({
    table: 'parcel_buildings',
    key: ['parcel_id', 'building_id'],
    columns: [{ name: 'parcel_id', vocabulary: 'none', written: 'step', bind: 'value', source: 'compute' }],
    write_discipline: { class: 'link_full_retraction', guard: 'none', guard_columns: 'all_declared', scope: 'parcel_id = ANY(batch ids) AND (parcel_id, building_id) NOT IN (derived keys)', expected_change_ratio: '<= 0.5', idempotent_rerun: 'zero_writes', txn_scope: 'batch' },
    retract: 'none',
    replay: 'idempotent_upsert',
    source_key_policy: { unique: true, on_collision: 'not_applicable', key_space_migration: 'none' },
  });
  d.outputs.writes.push({
    table: 'parcels',
    key: ['id'],
    columns: [{ name: 'massing_enriched_at', vocabulary: 'none', written: 'step', bind: 'value', source: 'compute' }],
    write_discipline: { class: 'set_based_scoped', set_source: 'compute', guard: 'none', guard_columns: 'all_declared', scope: 'id = ANY(parcels that lost a link this batch) AND massing_enriched_at IS NOT NULL', expected_change_ratio: '<= 1.0', idempotent_rerun: 'zero_writes', txn_scope: 'batch' },
    retract: 'none',
    replay: 'idempotent_upsert',
    source_key_policy: { unique: true, on_collision: 'not_applicable', key_space_migration: 'none' },
  });
  return d;
}

type Answer = { rows: unknown[]; rowCount?: number } | undefined;

/** E1's clear exactly as write.js generates it from the fixture descriptor. */
function e1ClearSql(): string {
  const d = row5Descriptor();
  return writeLib.buildWritePlan(d.outputs.writes[0], d).clear_sql;
}

function fakePool(answer: (text: string, values: unknown[]) => Answer) {
  const sql: string[] = [];
  const params: unknown[][] = [];
  const record = async (text: string, values?: unknown[]) => {
    sql.push(text);
    params.push(values ?? []);
    const custom = answer(text, values ?? []);
    if (custom !== undefined) return custom;
    if (/pg_extension|information_schema\.columns|pg_indexes|pg_constraint|pg_proc/i.test(text)) return { rows: [{ x: 1 }] };
    if (/relrowsecurity/i.test(text)) return { rows: [{ rls_enabled: false, policies: 0, bypassrls: true }] };
    return { rows: [], rowCount: 0 };
  };
  return { sql, params, query: record, connect: async () => ({ query: record, release: () => {} }) };
}

/** Answers keyed on the compute's OWN statement text, so the test drives the real SQL builders. */
function scenario(staleRows: Array<Record<string, unknown>>) {
  const m = compute.buildMatchSql(row5Descriptor(), CONFIG, 'full');
  let batchCalls = 0;
  return fakePool((text) => {
    if (text === m.eligible_count_sql) return { rows: [{ total: '3' }] };
    if (text === m.eligible_batch_sql) { batchCalls += 1; return batchCalls === 1 ? { rows: [{ id: 1 }, { id: 2 }, { id: 3 }] } : { rows: [] }; }
    if (text === m.primary_match_sql) return { rows: [
      { parcel_id: 1, building_id: 10, footprint_area_sqm: '120' },
      { parcel_id: 3, building_id: 30, footprint_area_sqm: '90' },
    ] };
    if (text === m.fallback_match_sql) return { rows: [] };
    if (text === m.cumulative_sql) return { rows: [{ linked: 2, total: 3 }] };
    if (text === m.stale_link_select_sql) return { rows: staleRows };
    if (text === m.lost_link_flag_sql) return { rows: staleRows.length > 0 ? [{ id: 2 }] : [], rowCount: staleRows.length > 0 ? 1 : 0 };
    if (text === m.stale_link_delete_sql) return { rows: [], rowCount: staleRows.length };
    if (text === e1ClearSql()) return { rows: [], rowCount: 0 };
    return undefined;
  });
}

async function run(pool: ReturnType<typeof fakePool>) {
  return stepLib.runLinkPhase({
    descriptor: row5Descriptor(), pool, compute, config: CONFIG, chainId: null,
    log: NOOP_LOG, tag: '[link_massing]', clockNow: RUN_AT,
  });
}

const STALE_20 = [{ parcel_id: 2, building_id: 20, is_primary: true, structure_type: 'primary', match_type: 'centroid_in_parcel', confidence: '0.95', linked_at: '2026-09-01T00:00:00Z' }];

afterEach(() => { vi.restoreAllMocks(); });

describe('O4 row 5 — link_massing full_rescan rewrites only changed links', () => {
  it('R5-1 (RED) — the compute supplies the four keyed statements, all scoped to the batch and guarded by the derived keys', () => {
    const m = compute.buildMatchSql(row5Descriptor(), CONFIG, 'full');
    // E1 stays a GENERATED set_based_scoped clear (lock #176); the guard is in its declared scope.
    expect(m.primary_clear_guarded_sql).toBeUndefined();
    const clear = e1ClearSql();
    expect(clear).toContain('UPDATE parcel_buildings SET is_primary = false');
    expect(clear).toContain(compute.PRIMARY_CLEAR_SCOPE);
    expect(compute.PRIMARY_CLEAR_SCOPE).toContain('is_primary = true');
    expect(compute.PRIMARY_CLEAR_SCOPE).toContain('NOT EXISTS (SELECT 1 FROM unnest($2::int[], $3::int[]) AS d(parcel_id, building_id)');
    expect(m.stale_link_delete_sql).toMatch(/^DELETE FROM parcel_buildings pb/);
    expect(m.stale_link_delete_sql).toContain('pb.parcel_id = ANY($1::int[])');
    expect(m.stale_link_delete_sql).toContain('NOT EXISTS (SELECT 1 FROM unnest($2::int[], $3::int[]) AS d(parcel_id, building_id)');
    expect(m.stale_link_delete_sql).not.toMatch(/\bUPDATE\b|\bINSERT\b/);
    expect(m.stale_link_select_sql).toMatch(/^SELECT pb\.parcel_id, pb\.building_id/);
    expect(m.lost_link_flag_sql).toMatch(/^UPDATE parcels SET massing_enriched_at = NULL/);
    expect(m.lost_link_flag_sql).toContain('massing_enriched_at IS NOT NULL');
    expect(m.lost_link_flag_sql).not.toMatch(/\bDELETE\b/);
    // the select and the delete use the SAME not-derived predicate (one fragment, cannot drift)
    const tail = (s: string) => s.slice(s.indexOf('WHERE'));
    expect(tail(m.stale_link_select_sql).replace(/;\s*$/, '')).toBe(tail(m.stale_link_delete_sql).replace(/;\s*$/, ''));
  });

  it('R5-2 (RED) — mode_select "none" resolves to a full rescan, and NO mass retraction DELETE is issued', async () => {
    vi.spyOn(writeLib, 'persistBeforeImageRows').mockReturnValue({ written: true, path: 'stub', rows: 1 });
    const pool = scenario(STALE_20);
    const result = await run(pool);
    expect(result.gate.mode).toBe('full');
    expect(result.gate.reason).toBe('full_rescan');
    const m = compute.buildMatchSql(row5Descriptor(), CONFIG, 'full');
    const deletes = pool.sql.filter((s) => /^\s*DELETE\b/i.test(s));
    expect(deletes, 'the ONLY delete is the keyed per-batch stale-link delete').toEqual([m.stale_link_delete_sql]);
  });

  it('R5-3 (RED) — (a) the unchanged primary (1,10) is EXCLUDED from the clear; (c) the new link (3,30) is upserted', async () => {
    vi.spyOn(writeLib, 'persistBeforeImageRows').mockReturnValue({ written: true, path: 'stub', rows: 1 });
    const pool = scenario(STALE_20);
    await run(pool);
    const ci = pool.sql.indexOf(e1ClearSql());
    expect(ci, 'the guarded clear is issued').toBeGreaterThanOrEqual(0);
    // $1 = every parcel in the batch; $2/$3 = the DERIVED primaries (kept, never cleared)
    expect(pool.params[ci]).toEqual([[1, 2, 3], [1, 3], [10, 30]]);
    const ui = pool.sql.findIndex((s) => /^\s*INSERT INTO parcel_buildings/i.test(s));
    expect(ui, 'the guarded upsert is issued').toBeGreaterThan(ci);
    const bound = pool.params[ui];
    expect(bound).toContain(30);
    expect(bound).toContain(10);
  });

  it('R5-4 (RED) — (b) the moved building\'s old link (2,20) is deleted and parcel 2 is flagged, in ONE transaction, flag before delete', async () => {
    const spy = vi.spyOn(writeLib, 'persistBeforeImageRows').mockReturnValue({ written: true, path: 'stub', rows: 1 });
    const pool = scenario(STALE_20);
    const result = await run(pool);
    const m = compute.buildMatchSql(row5Descriptor(), CONFIG, 'full');
    const si = pool.sql.indexOf(m.stale_link_select_sql);
    const fi = pool.sql.indexOf(m.lost_link_flag_sql);
    const di = pool.sql.indexOf(m.stale_link_delete_sql);
    const ui = pool.sql.findIndex((s) => /^\s*INSERT INTO parcel_buildings/i.test(s));
    expect(si).toBeGreaterThan(ui);
    expect(fi).toBeGreaterThan(si);
    expect(di).toBeGreaterThan(fi);
    // all derived keys keep their rows; everything else in the batch's parcels is stale
    expect(pool.params[si]).toEqual([[1, 2, 3], [1, 3], [10, 30]]);
    expect(pool.params[di]).toEqual([[1, 2, 3], [1, 3], [10, 30]]);
    expect(pool.params[fi]).toEqual([[2]]);
    // one transaction: BEGIN before the clear, COMMIT after the delete, no COMMIT in between
    const ci = pool.sql.indexOf(e1ClearSql());
    const begin = pool.sql.lastIndexOf('BEGIN', ci);
    const commit = pool.sql.indexOf('COMMIT', ci);
    expect(begin).toBeGreaterThanOrEqual(0);
    expect(begin).toBeLessThan(ci);
    expect(commit).toBeGreaterThan(di);
    // the destructive delete is before-imaged (R-M / LG-17) with the rows it is about to remove
    expect(spy).toHaveBeenCalledWith(STALE_20, 'parcel_buildings', REAL.identity.name, RUN_AT);
    // counted on the DECLARED targets: e3 = keyed delete, e4 = the parcels flag
    expect(result.written.e3.deleted).toBe(1);
    expect(result.written.e4.rows_changed).toBe(1);
  });

  it('R5-5 (RED) — steady state: nothing stale ⇒ no before-image, the flag binds an empty set, 0 deletes', async () => {
    const spy = vi.spyOn(writeLib, 'persistBeforeImageRows').mockReturnValue({ written: true, path: 'stub', rows: 0 });
    const pool = scenario([]);
    const result = await run(pool);
    const m = compute.buildMatchSql(row5Descriptor(), CONFIG, 'full');
    expect(spy).not.toHaveBeenCalled();
    expect(pool.params[pool.sql.indexOf(m.lost_link_flag_sql)]).toEqual([[]]);
    expect(result.written.e3.deleted).toBe(0);
    expect(result.written.e4.rows_changed).toBe(0);
  });

  it('R5-6 (RED) — an undeclared keyed write is refused: the compute supplies the delete but writes[] lacks the targets', async () => {
    const d = row5Descriptor();
    d.outputs.writes = d.outputs.writes.slice(0, 2);
    const pool = scenario([]);
    await expect(stepLib.runLinkPhase({
      descriptor: d, pool, compute, config: CONFIG, chainId: null,
      log: NOOP_LOG, tag: '[link_massing]', clockNow: RUN_AT,
    })).rejects.toThrow(/does not declare/);
  });

  it('R5-7 — an E1 clear whose declared scope lacks the derived-key guard is refused (an unchanged primary would be cleared and linked_at would move)', async () => {
    const d = row5Descriptor();
    d.outputs.writes[0].write_discipline.scope = 'parcel_id = ANY($1) AND is_primary = true';
    const pool = scenario([]);
    await expect(stepLib.runLinkPhase({
      descriptor: d, pool, compute, config: CONFIG, chainId: null,
      log: NOOP_LOG, tag: '[link_massing]', clockNow: RUN_AT,
    })).rejects.toThrow(/derived-key guard/);
  });
});
