/**
 * `recovery.reset === "generated"` -> reset SQL, plus the three destructive-reset
 * guards (STA-2 / STA-3, WF1 "state tables reset", 2026-09-03).
 *
 * WHY THIS EXISTS. `recovery.reset` (step.schema.json:1480) has been a declared field
 * only since Spec 120: every MATERIALIZER/BACKFILL descriptor satisfies the
 * `reset != "none"` profile requirement with a PROSE string ("TRUNCATE is never
 * correct here — re-run with …"), and nothing ever derived SQL from the "generated"
 * enum member. Programme item STA-2 (scripts/steps/_schema/programme-items.json)
 * measured that gap with 0 hits for a reset-SQL generator anywhere in
 * scripts/lib/step/. This file is the generator.
 *
 * `generateReset(descriptor)` reads ONLY `descriptor.recovery.reset` and
 * `descriptor.outputs.writes[]` and reuses `write.js`'s own plan builder
 * (`buildWritePlan`) so a reset statement is generated by the SAME codegen path a
 * live run's own retraction uses — never a second, drifting implementation. It
 * supports exactly the two write shapes `write.js`'s DEFAULT (unnamed) and
 * `set_based_null_retract` codegen paths can express safely:
 *   - `retract: "all"`                       -> `DELETE FROM <table> WHERE <scope>`
 *   - `write_discipline.class: "set_based_null_retract"` -> `UPDATE <table> SET
 *     <cols> = NULL WHERE <scope>`
 * NEVER `TRUNCATE` — every existing descriptor's own `recovery.reset` prose says
 * TRUNCATE is wrong for its table, and `scripts/validate-migration.js` already
 * treats it as a destructive statement requiring an explicit allow marker; nothing
 * here should reintroduce it through a second path.
 *
 * `retract: "departed"` and every DESCRIPTIVE-ONLY write_discipline.class
 * (`set_based_join_update`, `insert_only_no_retraction`, `write_once_backfill`,
 * `guarded_upsert` + `set_source:"compute"`, `link_full_retraction`) are
 * DELIBERATELY UNSUPPORTED here, even where `write.js` itself could technically
 * emit a statement (a departure DELETE, for instance) — those targets' real SQL is
 * either compute-authored or keyed by a live source set a dry-run reset has no
 * access to, and a generator that silently produced the wrong statement for one of
 * them is worse than one that refuses. `generateReset` THROWS naming the table,
 * write index, class and retract value so the refusal is actionable.
 *
 * `generateReset` is DRY-RUN BY DEFAULT (`{ execute: false }` unless the caller
 * passes `{ execute: true }`) — it always returns the statements it WOULD run; it
 * never opens a client or executes anything itself. `applyGeneratedReset` (STA-3)
 * is the only function in this file that touches a live connection, and it runs the
 * three guards below before issuing a single statement.
 *
 * STA-3 — three guards, each refusing BEFORE any statement runs:
 *   1. `assertBeforeImageDeclared` — no reset without a before-image (R-M,
 *      step.schema.json:1492-1496). Reuses `write.writeBeforeImage` verbatim.
 *   2. `assertForceFullAuthorized` — no reset outside a `chain_args` force_full
 *      authorization (R-L, Spec 124:188) — `override.force_full` must be true AND
 *      the slug's own `manifest.json scripts[slug].chain_args.sources` must declare
 *      `"--full"` (three converted steps already carry this shape today).
 *   3. `assertAdvisoryLockAvailable` — no reset while another run holds the step's
 *      advisory lock (`identity.lock`, §4.1② / index.js:2270). Uses the SAME
 *      `pg_try_advisory_xact_lock` primitive the runner's own `withAdvisoryLock`
 *      uses (pipeline.js:996) rather than a second locking mechanism.
 *
 * ⚠️ Delta from STA-3's original `promised` text ("dry-run default, explicit target
 * confirmation, one-txn magnitude+empty-source guard"): dry-run default survives
 * unchanged (`generateReset`'s own default). The other two guards are RE-DERIVED
 * from R-L and R-M, which post-date the original promise and are the stronger,
 * already-ratified mechanisms — recorded here, not silently substituted.
 *
 * SPEC LINK: docs/specs/01-pipeline/122_pipeline_step_optimization.md §7.5
 * SPEC LINK: docs/specs/01-pipeline/124_step_standard_policy.md R-L (:188), R-M (:189)
 */
'use strict';

const write = require('./write');

/** `recovery.reset` — the frozen non-prose enum members (step.schema.json:1480). */
const RESET_GENERATED = 'generated';
const RESET_NONE = 'none';

/** `write_discipline.class` this generator ALSO supports beyond the default codegen path. */
const SET_BASED_NULL_RETRACT_CLASS = 'set_based_null_retract';

/**
 * @param {string} slug - descriptor.identity.name, or "<unknown>" if absent
 * @param {number} index - 0-based position in outputs.writes[]
 * @param {object} writeSpec - the outputs.writes[] entry
 * @param {string} reason
 */
function unsupportedResetError(slug, index, writeSpec, reason) {
  const cls = writeSpec.write_discipline && writeSpec.write_discipline.class;
  const retract = writeSpec.retract || 'none';
  return new Error(
    `[generateReset] ${slug} outputs.writes[${index}] (table "${writeSpec.table}", `
    + `write_discipline.class "${cls}", retract "${retract}") declares recovery.reset "generated" `
    + `but ${reason}. This generator supports exactly two reset shapes: retract "all" (-> DELETE) `
    + 'and write_discipline.class "set_based_null_retract" (-> UPDATE ... SET NULL). Declare '
    + 'recovery.reset as a prose string instead, or extend generateReset (never reach for TRUNCATE).',
  );
}

/**
 * STA-2. Reads `descriptor.recovery.reset` and, when it is `"generated"`, derives
 * reset SQL for every destructive `outputs.writes[]` entry via `write.buildWritePlan`.
 *
 * @param {object} descriptor
 * @param {{ execute?: boolean }} [opts] - `execute` is carried through on the return
 *   value for the caller's own bookkeeping; this function NEVER executes anything
 *   itself regardless of the flag (dry-run is a property of this function's own
 *   contract, not a toggle it acts on).
 * @returns {{
 *   kind: 'none'|'declared_prose'|'generated',
 *   execute: boolean,
 *   statements: Array<{ table: string, kind: 'delete_all'|'set_null', sql: string, plan: object }>,
 * }}
 */
function generateReset(descriptor, opts = {}) {
  const execute = opts.execute === true;
  const slug = (descriptor.identity && descriptor.identity.name) || '<unknown>';
  const reset = descriptor.recovery && descriptor.recovery.reset;

  if (reset === undefined || reset === null || reset === RESET_NONE) {
    return { kind: 'none', execute, statements: [] };
  }
  if (reset !== RESET_GENERATED) {
    return { kind: 'declared_prose', execute, statements: [] };
  }

  const writes = (descriptor.outputs && descriptor.outputs.writes) || [];
  const statements = [];

  writes.forEach((writeSpec, index) => {
    const retract = writeSpec.retract || 'none';
    const cls = writeSpec.write_discipline && writeSpec.write_discipline.class;
    const isSetBasedNullRetract = cls === SET_BASED_NULL_RETRACT_CLASS;

    // A target with nothing to retract has nothing for a reset to tear down.
    if (retract === RESET_NONE && !isSetBasedNullRetract) return;

    if (retract === 'all') {
      const plan = write.buildWritePlan(writeSpec, descriptor);
      if (!plan.delete_sql) {
        throw unsupportedResetError(slug, index, writeSpec, 'retract "all" produced no delete_sql (a descriptive-only class whose SQL is compute-authored)');
      }
      statements.push({ table: plan.table, kind: 'delete_all', sql: plan.delete_sql, plan });
      return;
    }

    if (isSetBasedNullRetract) {
      const plan = write.buildWritePlan(writeSpec, descriptor);
      if (!plan.clear_sql) {
        throw unsupportedResetError(slug, index, writeSpec, 'write_discipline.class "set_based_null_retract" produced no clear_sql (likely set_source:"compute", which this generator does not support)');
      }
      statements.push({ table: plan.table, kind: 'set_null', sql: plan.clear_sql, plan });
      return;
    }

    // retract: "departed", or any other shape — deliberately unsupported (see file header).
    throw unsupportedResetError(slug, index, writeSpec, `retract "${retract}" is not one of the two reset shapes this generator supports`);
  });

  return { kind: RESET_GENERATED, execute, statements };
}

/**
 * STA-3 guard 1 — R-M. Any generated destructive statement requires
 * `recovery.before_image === "generated"`; refuses otherwise. A `resetPlan` with
 * zero statements (kind "none"/"declared_prose", or "generated" with nothing
 * destructive to retract) has nothing to guard and passes trivially.
 *
 * @param {object} descriptor
 * @param {{ statements: unknown[] }} resetPlan - from generateReset
 */
function assertBeforeImageDeclared(descriptor, resetPlan) {
  if (!resetPlan.statements || resetPlan.statements.length === 0) return;
  const beforeImage = descriptor.recovery && descriptor.recovery.before_image;
  if (beforeImage !== 'generated') {
    const slug = (descriptor.identity && descriptor.identity.name) || '<unknown>';
    throw new Error(
      `[generateReset guard 1/before_image] ${slug}: reset would run ${resetPlan.statements.length} `
      + `destructive statement(s) but recovery.before_image is "${beforeImage ?? 'undefined'}", not `
      + '"generated" (R-M, step.schema.json:1492-1496). Refusing — a destructive reset with no '
      + 'row-level before-image cannot be audited.',
    );
  }
}

/**
 * STA-3 guard 2 — R-L (Spec 124:188). A reset may run only under an
 * operator-authorized `override.force_full`, sourced from a chain whose
 * `manifest.json scripts[slug]` entry declares `chain_args: {"sources": ["--full"]}`
 * — never a bare corpus-signal or an autonomous schedule.
 *
 * @param {{ overrides?: {force_full?: boolean}, manifest: {scripts: Record<string, {chain_args?: {sources?: string[]}}>}, slug: string }} args
 */
function assertForceFullAuthorized({ overrides, manifest, slug } = {}) {
  if (!overrides || overrides.force_full !== true) {
    throw new Error(
      '[generateReset guard 2/force_full] reset refused: override.force_full is not true. A reset may '
      + 'run only under an operator-authorized force_full (R-L, Spec 124:188) sourced from a declared '
      + 'chain_args argv flag, never a bare corpus-signal or an autonomous trigger.',
    );
  }
  const entry = manifest && manifest.scripts && manifest.scripts[slug];
  const sources = (entry && entry.chain_args && entry.chain_args.sources) || [];
  if (!sources.includes('--full')) {
    throw new Error(
      `[generateReset guard 2/force_full] reset refused: manifest.json scripts["${slug}"] does not declare `
      + 'chain_args.sources including "--full" — force_full must be sourced from a declared argv flag '
      + '(R-L), not an autonomous/corpus-signal trigger.',
    );
  }
}

/**
 * STA-3 guard 3 — §4.1② / index.js:2270,2718. The SAME `pg_try_advisory_xact_lock`
 * primitive `pipeline.withAdvisoryLock` uses (pipeline.js:996), run on the caller's
 * own client/transaction so the acquisition and the reset statements that follow
 * share one transaction boundary. Refuses with `advisory_lock_held_elsewhere`
 * rather than racing a live writer.
 *
 * @param {{ query: (sql: string, params?: unknown[]) => Promise<{rows: Array<{acquired: boolean}>}> }} client
 * @param {number} lockId - descriptor.identity.lock
 */
async function assertAdvisoryLockAvailable(client, lockId) {
  const { rows } = await client.query('SELECT pg_try_advisory_xact_lock($1) AS acquired', [lockId]);
  const acquired = Boolean(rows && rows[0] && rows[0].acquired === true);
  if (!acquired) {
    throw new Error(
      `[generateReset guard 3/advisory_lock] reset refused: advisory_lock_held_elsewhere for lock id `
      + `${lockId} — another run holds it; refusing to race a live writer (index.js:2270 §4.1②, `
      + 'index.js:2718 precedent).',
    );
  }
  return true;
}

/**
 * The three guards, applied in order, followed by the before-image write (reusing
 * `write.writeBeforeImage` verbatim, on the SAME client, strictly before each
 * statement, unwrapped by try/catch per its own fail-loud contract) and the
 * statement itself. Not exercised by any live descriptor today (STA-2's own
 * grounding: 0 descriptors declare `recovery.reset: "generated"`) — provided so
 * the first `generated` declarer has a guarded executor to call rather than a raw
 * `client.query(stmt.sql)` loop.
 *
 * @param {import('pg').PoolClient} client
 * @param {object} descriptor
 * @param {ReturnType<typeof generateReset>} resetPlan
 * @param {{ overrides?: {force_full?: boolean}, manifest: object, runAt: Date }} args
 */
async function applyGeneratedReset(client, descriptor, resetPlan, { overrides, manifest, runAt } = {}) {
  const slug = (descriptor.identity && descriptor.identity.name) || '<unknown>';
  assertBeforeImageDeclared(descriptor, resetPlan);
  assertForceFullAuthorized({ overrides, manifest, slug });
  await assertAdvisoryLockAvailable(client, descriptor.identity && descriptor.identity.lock);

  const results = [];
  for (const stmt of resetPlan.statements) {
    // eslint-disable-next-line no-await-in-loop -- each statement's before-image must
    // land, and be committed to disk, strictly before that statement's own retraction.
    await write.writeBeforeImage(client, stmt.plan, [], slug, runAt);
    // eslint-disable-next-line no-await-in-loop -- same ordering requirement
    const result = await client.query(stmt.sql);
    results.push({ table: stmt.table, kind: stmt.kind, rowCount: result.rowCount || 0 });
  }
  return results;
}

module.exports = {
  generateReset,
  assertBeforeImageDeclared,
  assertForceFullAuthorized,
  assertAdvisoryLockAvailable,
  applyGeneratedReset,
  RESET_GENERATED,
  RESET_NONE,
  SET_BASED_NULL_RETRACT_CLASS,
};
