/**
 * `recovery.reset === "generated"` -> reset SQL (STA-2, WF1 "state tables reset",
 * 2026-09-03).
 *
 * WHY THIS EXISTS. `recovery.reset` (step.schema.json:1480) has been a declared field
 * only since Spec 120: every MATERIALIZER/BACKFILL descriptor satisfies the
 * `reset != "none"` profile requirement with a PROSE string ("TRUNCATE is never
 * correct here — re-run with …"), and nothing ever derived SQL from the "generated"
 * enum member. Programme item STA-2 (scripts/steps/_schema/programme-items.json)
 * measured that gap with 0 hits for a reset-SQL generator anywhere in
 * scripts/lib/step/. This file is the generator.
 *
 * `generateReset(descriptor)` reads ONLY `descriptor.recovery.reset` and
 * `descriptor.outputs.writes[]` and reuses `write.js`'s own plan builder
 * (`buildWritePlan`) so a reset statement is generated by the SAME codegen path a
 * live run's own retraction uses — never a second, drifting implementation. It
 * supports exactly the two write shapes `write.js`'s DEFAULT (unnamed) and
 * `set_based_null_retract` codegen paths can express safely:
 *   - `retract: "all"`                       -> `DELETE FROM <table> WHERE <scope>`
 *   - `write_discipline.class: "set_based_null_retract"` -> `UPDATE <table> SET
 *     <cols> = NULL WHERE <scope>`
 * NEVER `TRUNCATE` — every existing descriptor's own `recovery.reset` prose says
 * TRUNCATE is wrong for its table, and `scripts/validate-migration.js` already
 * treats it as a destructive statement requiring an explicit allow marker; nothing
 * here should reintroduce it through a second path.
 *
 * `retract: "departed"` and every DESCRIPTIVE-ONLY write_discipline.class
 * (`set_based_join_update`, `insert_only_no_retraction`, `write_once_backfill`,
 * `guarded_upsert` + `set_source:"compute"`, `link_full_retraction`) are
 * DELIBERATELY UNSUPPORTED here, even where `write.js` itself could technically
 * emit a statement (a departure DELETE, for instance) — those targets' real SQL is
 * either compute-authored or keyed by a live source set a dry-run reset has no
 * access to, and a generator that silently produced the wrong statement for one of
 * them is worse than one that refuses. `generateReset` THROWS naming the table,
 * write index, class and retract value so the refusal is actionable.
 *
 * `generateReset` is DRY-RUN BY DEFAULT (`{ execute: false }` unless the caller
 * passes `{ execute: true }`) — it always returns the statements it WOULD run; it
 * never opens a client or executes anything itself. The three destructive-reset
 * guards (STA-3: no reset without a before-image, no reset outside a `chain_args`
 * force_full authorization, no reset while another run holds the advisory lock)
 * land in a follow-on commit — this file is `generateReset` alone.
 *
 * SPEC LINK: docs/specs/01-pipeline/122_pipeline_step_optimization.md §7.5b
 */
'use strict';

const write = require('./write');

/** `recovery.reset` — the frozen non-prose enum members (step.schema.json:1480). */
const RESET_GENERATED = 'generated';
const RESET_NONE = 'none';

/** `write_discipline.class` this generator ALSO supports beyond the default codegen path. */
const SET_BASED_NULL_RETRACT_CLASS = 'set_based_null_retract';

/**
 * @param {string} slug - descriptor.identity.name, or "<unknown>" if absent
 * @param {number} index - 0-based position in outputs.writes[]
 * @param {object} writeSpec - the outputs.writes[] entry
 * @param {string} reason
 */
function unsupportedResetError(slug, index, writeSpec, reason) {
  const cls = writeSpec.write_discipline && writeSpec.write_discipline.class;
  const retract = writeSpec.retract || 'none';
  return new Error(
    `[generateReset] ${slug} outputs.writes[${index}] (table "${writeSpec.table}", `
    + `write_discipline.class "${cls}", retract "${retract}") declares recovery.reset "generated" `
    + `but ${reason}. This generator supports exactly two reset shapes: retract "all" (-> DELETE) `
    + 'and write_discipline.class "set_based_null_retract" (-> UPDATE ... SET NULL). Declare '
    + 'recovery.reset as a prose string instead, or extend generateReset (never reach for TRUNCATE).',
  );
}

/**
 * STA-2. Reads `descriptor.recovery.reset` and, when it is `"generated"`, derives
 * reset SQL for every destructive `outputs.writes[]` entry via `write.buildWritePlan`.
 *
 * @param {object} descriptor
 * @param {{ execute?: boolean }} [opts] - `execute` is carried through on the return
 *   value for the caller's own bookkeeping; this function NEVER executes anything
 *   itself regardless of the flag (dry-run is a property of this function's own
 *   contract, not a toggle it acts on).
 * @returns {{
 *   kind: 'none'|'declared_prose'|'generated',
 *   execute: boolean,
 *   statements: Array<{ table: string, kind: 'delete_all'|'set_null', sql: string, plan: object }>,
 * }}
 */
function generateReset(descriptor, opts = {}) {
  const execute = opts.execute === true;
  const slug = (descriptor.identity && descriptor.identity.name) || '<unknown>';
  const reset = descriptor.recovery && descriptor.recovery.reset;

  if (reset === undefined || reset === null || reset === RESET_NONE) {
    return { kind: 'none', execute, statements: [] };
  }
  if (reset !== RESET_GENERATED) {
    return { kind: 'declared_prose', execute, statements: [] };
  }

  const writes = (descriptor.outputs && descriptor.outputs.writes) || [];
  const statements = [];

  writes.forEach((writeSpec, index) => {
    const retract = writeSpec.retract || 'none';
    const cls = writeSpec.write_discipline && writeSpec.write_discipline.class;
    const isSetBasedNullRetract = cls === SET_BASED_NULL_RETRACT_CLASS;

    // A target with nothing to retract has nothing for a reset to tear down.
    if (retract === RESET_NONE && !isSetBasedNullRetract) return;

    if (retract === 'all') {
      const plan = write.buildWritePlan(writeSpec, descriptor);
      if (!plan.delete_sql) {
        throw unsupportedResetError(slug, index, writeSpec, 'retract "all" produced no delete_sql (a descriptive-only class whose SQL is compute-authored)');
      }
      statements.push({ table: plan.table, kind: 'delete_all', sql: plan.delete_sql, plan });
      return;
    }

    if (isSetBasedNullRetract) {
      const plan = write.buildWritePlan(writeSpec, descriptor);
      if (!plan.clear_sql) {
        throw unsupportedResetError(slug, index, writeSpec, 'write_discipline.class "set_based_null_retract" produced no clear_sql (likely set_source:"compute", which this generator does not support)');
      }
      statements.push({ table: plan.table, kind: 'set_null', sql: plan.clear_sql, plan });
      return;
    }

    // retract: "departed", or any other shape — deliberately unsupported (see file header).
    throw unsupportedResetError(slug, index, writeSpec, `retract "${retract}" is not one of the two reset shapes this generator supports`);
  });

  return { kind: RESET_GENERATED, execute, statements };
}

module.exports = {
  generateReset,
  RESET_GENERATED,
  RESET_NONE,
  SET_BASED_NULL_RETRACT_CLASS,
};
